In [86]:
import tensorflow as tf
import numpy as np

### scaler data

In [87]:
s1 = 10
s2 = 3.14
s3 = 'abc'

### vector data

In [88]:
v = [10,20,30]

### matrix data

In [89]:
m = [ [10,20,30], [40,50,60] ] # 2x3

### 3d tensor

In [90]:
d3 =[ [ [10,20,30], [40,50,60] ],  [ [10,20,30], [40,50,60] ] ] # 2x2x3

### 4d tensor

In [91]:
d4 =[ [ [ [10,20,30], [40,50,60] ],  [ [10,20,30], [40,50,60] ] ],
[ [ [10,20,30], [40,50,60] ],  [ [10,20,30], [40,50,60] ] ] ] # 2x2x2x3

### 텐서 데이터 노드 정의 하는 방법
- constant : 읽기 전용 (변경 불가, 고정값)
- Variable : 읽기 쓰기

In [92]:
s1 = 10
c1 = tf.constant( s1 )
print( type(c1) )
c1

<class 'tensorflow.python.framework.ops.EagerTensor'>


<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [93]:
c1.numpy()

np.int32(10)

In [94]:
v1 = tf.constant( [ 10,20,30 ] )
v1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30], dtype=int32)>

In [95]:
v1.numpy()

array([10, 20, 30], dtype=int32)

In [96]:
m1 = tf.constant( [ [10,20,30], [40,50,60] ] )
m1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)>

### 사칙연산 : add(+), sub(-), multiply(*), div(/)
- broad casting
- element wise

In [97]:
a = tf.constant(3)
b = tf.constant( [1,2,3] )
# c = tf.add(a,b)
# c = a+b
# c = tf.multiply(a,b)
c = a*b
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9], dtype=int32)>

In [98]:
c.numpy()

array([3, 6, 9], dtype=int32)

In [99]:
d = tf.add(a,b)
d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6], dtype=int32)>

In [100]:
e = c+d
e

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 7, 11, 15], dtype=int32)>

In [101]:
f = tf.constant([ 1, 2, 3] )
g = tf.constant([ [1, 2, 3], [4, 5, 6], [7, 8, 9],] )
h = f+g # tf.add(f,g)
h

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]], dtype=int32)>

### 행렬곱

In [102]:
o = tf.constant([[1,2],[3,4]])
p = tf.constant([[5,6],[7,8]])
q = tf.multiply(o,p)
r = tf.matmul(o,p)

In [103]:
q.numpy()

array([[ 5, 12],
       [21, 32]], dtype=int32)

In [104]:
r.numpy()

array([[19, 22],
       [43, 50]], dtype=int32)

### 많이 사용하는 연산

In [109]:
s = tf.constant([1,2,3])
# t = tf.square(s)
t = s**2
t

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

In [110]:
u = tf.reduce_mean(s)
u

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [111]:
v = tf.reduce_sum(s)
v

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [115]:
v = tf.Variable(10) # Variable의 경우 값 변경 가능
v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [ ]:
v.assign(20) # 10 -> 20 변경
v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=20>

In [ ]:
v.assign_add(2) # 20 + 2 
v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=22>

In [ ]:
v.assign_sub(3) # 22 - 3 , 가장 사용 多 
v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=19>