In [23]:
import tensorflow as tf
from keras.optimizers import Adam
from keras import Sequential
from keras.layers import Dense
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

In [24]:
df = pd.read_csv('data/test.csv', header=None)
df.columns = ['q1', 'q2', 'mid', 'final']
df

,q1,q2,mid,final
0,73,80,75,152
1,93,88,93,185
2,89,91,90,180
3,96,98,100,196
4,73,66,70,142
5,53,46,55,101
6,69,74,77,149
7,47,56,60,115
8,87,79,90,175
9,79,70,88,164


In [25]:
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [26]:
x.shape

(25, 3)

In [27]:
# 1. hx = matmul(x,w) + b
# 2. w[3,1], b[1]
dense = Dense(units=1, input_dim=3)
print(dense(x)) #  hx = matmul(x,w) + b
w, b = dense.get_weights() # 학습되지 않은 상태에서 예측 값 추출해 봄
print(w)
print(b)

tf.Tensor(
[[ 9.671794 ]
 [15.803469 ]
 [13.366734 ]
 [15.183596 ]
 [12.574342 ]
 [10.723982 ]
 [11.1229725]
 [ 7.7835484]
 [16.503304 ]
 [17.043018 ]
 [11.319302 ]
 [13.2447815]
 [13.244495 ]
 [10.398319 ]
 [11.867504 ]
 [16.246696 ]
 [10.44059  ]
 [12.775324 ]
 [11.883739 ]
 [10.294088 ]
 [13.420948 ]
 [15.168297 ]
 [12.263329 ]
 [ 8.41088  ]
 [15.4290085]], shape=(25, 1), dtype=float32)
[[ 0.20313907]
 [-0.2952373 ]
 [ 0.24615502]]
[0.]


c:\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [28]:
dense = Dense(units=1, input_dim=3)
model = Sequential( [dense] ) # dense의 w와 b가 학습 대상
model.compile( loss='mse', optimizer=Adam(0.1))
model.fit(x, y, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 216ms/step - loss: 24408.7051
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 17404.4316
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 11626.9990
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 7080.1982
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 3739.8721
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 1542.5624
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 374.2773
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 63.3353
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 384.2045
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1078.2382
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1889.9503
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 2607.1943
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 3089.3518
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 3274.6150
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23

In [29]:
w, b = dense.get_weights() # 학습된 상태
print(w)
print(b)

[[1.3190283 ]
 [0.3347089 ]
 [0.37278208]]
[0.79039156]


In [30]:
dense(x) # tensor 객체라 np.array로 주어야함

<tf.Tensor: shape=(25, 1), dtype=float32, numpy=
array([[151.81482],
       [187.58313],
       [182.1928 ],
       [197.49678],
       [145.26498],
       [106.59851],
       [145.27602],
       [103.89534],
       [175.53824],
       [161.22807],
       [142.44604],
       [142.46432],
       [189.18053],
       [158.98343],
       [146.63312],
       [189.03618],
       [154.12694],
       [172.42421],
       [179.71736],
       [160.15965],
       [171.28606],
       [174.85057],
       [163.1419 ],
       [155.2849 ],
       [193.95934]], dtype=float32)>

In [31]:
model.predict(x) # 1. 기본 전처리 2. dense(x) 3. 결과를 numpy로 출력

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step


array([[151.81482],
       [187.58313],
       [182.1928 ],
       [197.49678],
       [145.26498],
       [106.59851],
       [145.27602],
       [103.89534],
       [175.53824],
       [161.22807],
       [142.44604],
       [142.46432],
       [189.18053],
       [158.98343],
       [146.63312],
       [189.03618],
       [154.12694],
       [172.42421],
       [179.71736],
       [160.15965],
       [171.28606],
       [174.85057],
       [163.1419 ],
       [155.2849 ],
       [193.95934]], dtype=float32)

q1:73, q2:80, mid:75, final:152

In [32]:
model.predict(np.array([[73,80,75]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step


array([[151.81482]], dtype=float32)