In [ ]:
import tensorflow as tf
from keras.optimizers import Adam
from keras import Sequential
from keras.layers import Dense
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

In [ ]:
df = pd.read_csv('data/softmax.txt', sep=' ', header=None)
df

,0,1,2,3,4
0,2,1,0,0,1
1,3,2,0,0,1
2,3,4,0,0,1
3,5,5,0,1,0
4,7,5,0,1,0
5,2,5,0,1,0
6,6,6,1,0,0
7,7,7,1,0,0


In [ ]:
x_data = df.iloc[:, :2].values
y_data = df.iloc[:, 2:].values

In [ ]:
x = tf.constant(x_data, tf.float32)
y = tf.constant(y_data, tf.float32)

In [ ]:
initX = tf.initializers.GlorotUniform()
w = tf.Variable(initX(shape=[2,3])) # [특정데이터 갯수, 라벨의 갯수]
b = tf.Variable(initX(shape=[3])) # [라벨의 갯수]

In [ ]:
lr = 0.01
optimizer = tf.keras.optimizers.Adam(learning_rate=lr)
for i in range(2000):
    with tf.GradientTape() as tape: # 미분 대상 함수 with로 지정
        z = tf.matmul(x,w) + b
        cost_i = tf.nn.softmax_cross_entropy_with_logits(labels=y, logits= z )
        cost = tf.reduce_mean( cost_i)
    
    gradients = tape.gradient( cost, [w,b] )
    optimizer.apply_gradients(zip(gradients, [w,b]))
    print( 'cost', cost.numpy()) #y축

print('최종w', w.numpy()) # 최종w [[ 0.15967649  0.06876978 -0.14740367]
                            #  [ 1.513369   -0.15485252 -1.7940806 ]]
print('최종b', b.numpy()) # 최종b [-9.598209    0.46163747  7.8739443 ]

cost 3.6321952
cost 3.5195045
cost 3.4086452
cost 3.2999067
cost 3.1936224
cost 3.0901704
cost 2.9899848
cost 2.893556
cost 2.8014314
cost 2.714207
cost 2.632507
cost 2.5569487
cost 2.4880824
cost 2.4263165
cost 2.371832
cost 2.3245034
cost 2.2838564
cost 2.249071
cost 2.2190523
cost 2.192544
cost 2.1682634
cost 2.1450248
cost 2.1218295
cost 2.0979142
cost 2.072757
cost 2.04606
cost 2.017714
cost 1.9877595
cost 1.956348
cost 1.9237065
cost 1.8901087
cost 1.8558495
cost 1.8212239
cost 1.7865112
cost 1.751961
cost 1.7177848
cost 1.6841481
cost 1.651168
cost 1.618915
cost 1.5874146
cost 1.5566545
cost 1.5265933
cost 1.4971707
cost 1.4683161
cost 1.4399611
cost 1.412046
cost 1.3845282
cost 1.3573866
cost 1.3306255
cost 1.3042753
cost 1.2783922
cost 1.2530563
cost 1.228368
cost 1.2044454
cost 1.1814181
cost 1.1594241
cost 1.1386039
cost 1.1190965
cost 1.1010332
cost 1.0845323
cost 1.069694
cost 1.0565948
cost 1.0452805
cost 1.0357621
cost 1.0280101
cost 1.021952
cost 1.0174713
cost 1.014408

In [ ]:
def hxFn( xd ):
    xd = tf.constant(xd, tf.float32)
    z = tf.matmul(xd, w) + b
    hx = tf.nn.softmax(z)
    return hx.numpy(), np.argmax( hx.numpy(), axis=1)

In [ ]:
hxFn( [[5,6]] )

(array([[0.5531025 , 0.42928278, 0.0176147 ]], dtype=float32), array([0]))

In [ ]:
# 토론 후
# iris 데이터 셋 학습 첫 번째, 두 번째 행의 분류를 예측


In [ ]:
from keras.utils import to_categorical

In [ ]:
xdata = np.array([0,0,0,1,1,1,2,2,2]) 
to_categorical(xdata) # 원핫으로 변경

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris(as_frame=True)
iris['frame']

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2


In [ ]:
x_data = iris['data'].values
y_data = to_categorical(iris['target'])

In [ ]:
x = tf.constant(x_data, tf.float32)
y = tf.constant(y_data, tf.float32)

In [ ]:
initX = tf.initializers.GlorotUniform()
w = tf.Variable(initX(shape=[4,3])) # [특정데이터 갯수, 라벨의 갯수]
b = tf.Variable(initX(shape=[3])) # [라벨의 갯수]

In [ ]:
lr = 0.01
optimizer = tf.keras.optimizers.Adam(learning_rate=lr)
for i in range(2000):
    with tf.GradientTape() as tape: # 미분 대상 함수 with로 지정
        z = tf.matmul(x,w) + b
        cost_i = tf.nn.softmax_cross_entropy_with_logits(labels=y, logits= z )
        cost = tf.reduce_mean( cost_i)
    
    gradients = tape.gradient( cost, [w,b] )
    optimizer.apply_gradients(zip(gradients, [w,b]))
    print( 'cost', cost.numpy()) #y축

print('최종w', w.numpy()) #최종w [[ 0.86472356  0.7664048  -0.6165995 ]
                            #   [ 2.8612015   0.27341866 -1.9434301 ]
                            #   [-2.7304587  -0.327513    1.5811676 ]
                            #   [-3.537929   -1.9434179   3.9583986 ]]
print('최종b', b.numpy()) # 최종b [ 1.5409434  2.174335  -1.8778523]

cost 8.00314
cost 7.8271356
cost 7.6511865
cost 7.475306
cost 7.299515
cost 7.123836
cost 6.9482975
cost 6.772936
cost 6.5977955
cost 6.422933
cost 6.248418
cost 6.0743375
cost 5.900797
cost 5.727927
cost 5.5558877
cost 5.38487
cost 5.2151027
cost 5.046856
cost 4.880445
cost 4.71623
cost 4.5546117
cost 4.3960285
cost 4.240945
cost 4.0898385
cost 3.9431837
cost 3.8014364
cost 3.6650195
cost 3.5343099
cost 3.409629
cost 3.2912369
cost 3.1793096
cost 3.0739143
cost 2.9749653
cost 2.8821752
cost 2.7950127
cost 2.712702
cost 2.6342628
cost 2.5585985
cost 2.484603
cost 2.411262
cost 2.3377333
cost 2.2633874
cost 2.1878197
cost 2.1108375
cost 2.0324311
cost 1.9527354
cost 1.8719946
cost 1.790523
cost 1.7086763
cost 1.6268281
cost 1.5453514
cost 1.464613
cost 1.3849721
cost 1.306787
cost 1.2304268
cost 1.1562885
cost 1.0848134
cost 1.0165033
cost 0.95193124
cost 0.8917418
cost 0.83663446
cost 0.787327
cost 0.7444931
cost 0.70867985
cost 0.6802124
cost 0.65910894
cost 0.64502686
cost 0.6372606


In [ ]:
w.shape

TensorShape([4, 3])

In [ ]:
def hxFn( xd ):
    xd = tf.constant(xd, tf.float32)
    z = tf.matmul(xd, w) + b
    hx = tf.nn.softmax(z)
    return hx.numpy(), np.argmax( hx.numpy(), axis=1)

In [ ]:
x_data[[0,1]]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [ ]:
hxFn(x_data[[0,1]])

(array([[9.9473947e-01, 5.2605360e-03, 1.5900731e-09],
        [9.8071003e-01, 1.9289946e-02, 2.3293067e-08]], dtype=float32),
 array([0, 0]))

In [ ]:
np.argmax(y_data[[0,1]], axis=1)

array([0, 0])