In [122]:
import tensorflow as tf
from keras.optimizers import Adam
from keras import Sequential
from keras.layers import Dense, Input
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

In [123]:
x = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0],[1],[1],[0]])

In [124]:
# deep하게 잡아서 acc 값 1.00으로 출력됨
dense1 = Dense(units=100, input_dim=2, activation='sigmoid') # 2X100 b:100
dense2 = Dense(units=1, input_dim=100, activation='sigmoid') # 100X1 b:1
model = Sequential( [dense1, dense2] )
model.compile(loss='binary_crossentropy', optimizer=Adam(0.1), metrics=['acc']) # acc : 정확도를 출력해줌
h = model.fit(x, y, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 319ms/step - acc: 0.5000 - loss: 0.8170
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.5000 - loss: 2.3557
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - acc: 0.5000 - loss: 1.3364
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.5000 - loss: 0.7693
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - acc: 0.5000 - loss: 1.3224
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.5000 - loss: 1.2542
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.5000 - loss: 0.8602
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 0.5000 - loss: 0.7000
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.5000 - loss: 0.8901
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.5000 - loss: 1.0033
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.5000 - loss: 0.9290
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 0.5000 - loss: 0.7733
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/st

In [ ]:
# forward 연산
# 4X2 2X100 = 4X100
hx1 = dense1(x) # z1 = matmul(x, w1) + b1  hx1 = sigmoid(z1)
# 4X100 100X1 = 4X1
hx = dense2(hx1) # z = matmul(hx1, w2) + b2  hx = sigmoid(z)
hx

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[2.7344545e-04],
       [9.9940318e-01],
       [9.9943596e-01],
       [1.2947120e-03]], dtype=float32)>

In [126]:
model.predict(x)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step


array([[2.7344545e-04],
       [9.9940318e-01],
       [9.9943596e-01],
       [1.2947122e-03]], dtype=float32)

In [127]:
(model.predict(x) > 0.5) + 0 

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


array([[0],
       [1],
       [1],
       [0]])

In [ ]:
# deep하게 잡아서 acc 값 1.00으로 출력됨
dense1 = Dense(units=32, input_dim=2, activation='sigmoid')  # 2X32 b:32
dense2 = Dense(units=16, input_dim=32, activation='sigmoid') # 32X16 b:16
dense3 = Dense(units=1, input_dim=16, activation='sigmoid')  # 16X1 b:1
model = Sequential( [dense1, dense2, dense3] )
model.compile(loss='binary_crossentropy', optimizer=Adam(0.1), metrics=['acc']) # acc : 정확도를 출력해줌
h = model.fit(x, y, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 649ms/step - acc: 0.5000 - loss: 0.6931
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.5000 - loss: 1.2207
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - acc: 0.5000 - loss: 0.7469
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.5000 - loss: 0.8385
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.5000 - loss: 0.8494
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.5000 - loss: 0.7645
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.5000 - loss: 0.7098
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 0.5000 - loss: 0.6933
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 0.5000 - loss: 0.6935
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.5000 - loss: 0.6982
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.5000 - loss: 0.7022
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.5000 - loss: 0.7036
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/st

In [129]:
# Input 내장함수를 통해 input_dim 생략 가능 (권장사항)
myin = Input(shape=(2,)) # 입력층: Input layer
dense1 = Dense(units=32, activation='sigmoid') # 2X32  b:32  # hidden layer
dense2 = Dense(units=16, activation='sigmoid') # 32X16 b:16  # hidden layer
dense3 = Dense(units=1,  activation='sigmoid') # 16X1  b:1   # output layer
model = Sequential( [myin, dense1, dense2, dense3] )
model.compile(loss='binary_crossentropy', optimizer=Adam(0.1), metrics=['acc']) # acc : 정확도를 출력해줌
h = model.fit(x, y, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 399ms/step - acc: 0.5000 - loss: 0.7632
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.5000 - loss: 0.8987
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.5000 - loss: 0.8120
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.5000 - loss: 0.7163
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.5000 - loss: 0.6937
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - acc: 0.5000 - loss: 0.7130
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - acc: 0.5000 - loss: 0.7274
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.5000 - loss: 0.7235
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.5000 - loss: 0.7109
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.5000 - loss: 0.6997
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 0.5000 - loss: 0.6941
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.5000 - loss: 0.6936
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/st

In [130]:
# 4X2 2X32 = 4X32
hx1 = dense1(x)   # z1 = matmul(x, w1) + b1    hx1 = sigmoid(z1)
# 4X32 32X16 = 4X16
hx2 = dense2(hx1) # z2 = matmul(hx1, w2) + b2  hx2 = sigmoid(z2)
# 4X16 16X1 = 4X1
hx = dense3(hx2)  # z = matmul(hx2, w3) + b3   hx = sigmoid(z)
hx

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[5.2482581e-05],
       [9.9990636e-01],
       [9.9991065e-01],
       [1.0617955e-03]], dtype=float32)>

In [131]:
model.predict(x)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


array([[5.2482585e-05],
       [9.9990636e-01],
       [9.9991065e-01],
       [1.0617954e-03]], dtype=float32)

In [132]:
(model.predict(x) > 0.5) + 0 

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step


array([[0],
       [1],
       [1],
       [0]])

### hidden layer : ReRU

In [ ]:
myin = Input(shape=(2,)) # 입력층: Input layer
dense1 = Dense(units=32, activation='relu')    # 2X32  b:32  # hidden layer
dense2 = Dense(units=16, activation='relu')    # 32X16 b:16  # hidden layer
dense3 = Dense(units=1,  activation='sigmoid') # 16X1  b:1   # output layer
model = Sequential( [myin, dense1, dense2, dense3] )
model.compile(loss='binary_crossentropy', optimizer=Adam(0.1), metrics=['acc']) # acc : 정확도를 출력해줌
h = model.fit(x, y, epochs=100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 397ms/step - acc: 0.5000 - loss: 0.6976
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.5000 - loss: 0.7527
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 0.5000 - loss: 0.6826
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.7500 - loss: 0.6594
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.7500 - loss: 0.6382
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.7500 - loss: 0.5982
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 1.0000 - loss: 0.5516
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.5002
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 1.0000 - loss: 0.4259
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 1.0000 - loss: 0.3612
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 1.0000 - loss: 0.2988
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 1.0000 - loss: 0.2252
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/st

In [134]:
### 퀴즈: iris dataset 딥러닝으로 구성해서 train, test 의 정확도 확인 (정규화X)

In [151]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from sklearn.metrics import accuracy_score

In [152]:
iris = load_iris(as_frame=True)
iris['frame']

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2


In [153]:
x = iris['data'].values
y = to_categorical(iris['target'])

In [154]:
x.shape

(150, 4)

In [155]:
y.shape

(150, 3)

In [156]:
myin = Input(shape=(4,)) # 입력층: Input layer
dense1 = Dense(units=32, activation='relu')    # hidden layer
dense2 = Dense(units=16, activation='relu')    # hidden layer
dense3 = Dense(units=3,  activation='softmax') # output layer
model = Sequential( [myin, dense1, dense2, dense3] )
model.compile(loss='categorical_crossentropy', optimizer=Adam(0.01), metrics=['acc']) # acc : 정확도를 출력해줌
h = model.fit(x, y, epochs=100)

Epoch 1/100


5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.5067 - loss: 1.0205  
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.7533 - loss: 0.7810 
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8000 - loss: 0.6443 
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.7467 - loss: 0.5036 
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9800 - loss: 0.4032 
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9067 - loss: 0.3387 
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9733 - loss: 0.2836 
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9600 - loss: 0.2456 
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9733 - loss: 0.2051 
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9400 - loss: 0.1930 
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9400 - loss: 0.1797
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9733 - loss: 0.1407 
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.97

In [157]:
y_pred = model.predict(x).argmax(axis=1)
y_pred

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step 


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [158]:
accuracy_score(y.argmax(axis=1), y_pred)

0.9866666666666667

In [159]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42, stratify=y)

In [160]:
x_train.shape

(105, 4)

In [161]:
y_train.shape

(105, 3)

In [162]:
myin = Input(shape=(4,)) # 입력층: Input layer
dense1 = Dense(units=32, activation='relu')    # hidden layer
dense2 = Dense(units=16, activation='relu')    # hidden layer
dense3 = Dense(units=3,  activation='softmax') # output layer
model = Sequential( [myin, dense1, dense2, dense3] )
model.compile(loss='categorical_crossentropy', optimizer=Adam(0.01), metrics=['acc']) # acc : 정확도를 출력해줌
h = model.fit(x_train, y_train, epochs=500)

Epoch 1/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.2857 - loss: 1.0909  
Epoch 2/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.6667 - loss: 0.8790 
Epoch 3/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.6762 - loss: 0.7239 
Epoch 4/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.6667 - loss: 0.6295 
Epoch 5/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.7238 - loss: 0.5342 
Epoch 6/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.8286 - loss: 0.4590 
Epoch 7/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - acc: 0.7238 - loss: 0.4186 
Epoch 8/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.8000 - loss: 0.4147 
Epoch 9/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.7619 - loss: 0.3784 
Epoch 10/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.7619 - loss: 0.3673 
Epoch 11/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9048 - loss: 0.3327 
Epoch 12/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9048 - loss: 0.3090 
Epoch 13/500
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/ste

In [163]:
pred = model.predict(x_train).argmax(axis=1)
pred

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step 


array([1, 1, 2, 0, 1, 0, 2, 2, 2, 0, 0, 2, 2, 1, 1, 0, 2, 2, 0, 1, 2, 0,
       0, 0, 1, 2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 0, 0, 2, 0, 2, 0, 2,
       0, 1, 2, 0, 1, 0, 1, 2, 1, 0, 1, 0, 2, 1, 2, 1, 1, 1, 0, 2, 1, 0,
       0, 2, 0, 1, 1, 0, 2, 0, 0, 1, 2, 0, 0, 2, 2, 0, 0, 0, 2, 0, 1, 0,
       0, 2, 1, 1, 1, 1, 1, 2, 0, 1, 0, 2, 2, 1, 1, 1, 2])

In [164]:
accuracy_score(y_train.argmax(axis=1), pred)

0.9809523809523809

In [165]:
pred_t = model.predict(x_test).argmax(axis=1)
pred_t

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step


array([0, 1, 0, 1, 0, 0, 1, 1, 2, 0, 2, 1, 0, 0, 2, 0, 1, 2, 2, 2, 1, 2,
       1, 0, 0, 1, 1, 1, 1, 2, 0, 0, 1, 2, 0, 2, 2, 2, 2, 1, 1, 2, 0, 0,
       1])

In [166]:
accuracy_score(y_test.argmax(axis=1), pred_t)

0.9777777777777777