In [39]:
import tensorflow as tf
from keras.optimizers import Adam
from keras import Sequential, Model
from keras.layers import Dense, Input
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

In [40]:
x = np.array([[0,0], [0,1], [1,0], [1,1]], np.float32)
y = np.array([[0],[1],[1],[0]], np.float32)

### model 1

In [ ]:
# deep하게 잡아서 acc 값 1.00으로 출력됨
myin = Input(shape=(2,))
dense1 = Dense(units=100, activation='relu')   # 2X100 b:100
dense2 = Dense(units=1,  activation='sigmoid') # 100X1 b:1
model = Sequential( [dense1, dense2] )
model.compile(loss='binary_crossentropy', optimizer=Adam(0.1), metrics=['acc']) # acc : 정확도를 출력해줌
h = model.fit(x, y, epochs=100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 390ms/step - acc: 0.7500 - loss: 0.6918
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 0.2500 - loss: 0.6622
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.5000 - loss: 0.6976
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.7500 - loss: 0.5107
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 1.0000 - loss: 0.4521
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 1.0000 - loss: 0.3618
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 1.0000 - loss: 0.2428
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 1.0000 - loss: 0.1496
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 1.0000 - loss: 0.0985
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 1.0000 - loss: 0.0608
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - acc: 1.0000 - loss: 0.0355
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 1.0000 - loss: 0.0184
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/st

### model 2 (사용 多)

In [42]:
model = Sequential()
model.add(Input(shape=(2,)))
model.add( Dense(units=100, activation='relu'))
model.add( Dense(units=1,   activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer=Adam(0.1), metrics=['acc'])
h = model.fit(x, y, epochs=100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 332ms/step - acc: 0.5000 - loss: 0.6861
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 0.5000 - loss: 0.8993
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 0.5000 - loss: 0.6179
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 1.0000 - loss: 0.6177
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - acc: 1.0000 - loss: 0.6206
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - acc: 1.0000 - loss: 0.5964
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.5416
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 1.0000 - loss: 0.4659
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 1.0000 - loss: 0.3927
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 1.0000 - loss: 0.3289
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.2755
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 1.0000 - loss: 0.2218
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/st

In [43]:
w,b = model.layers[0].get_weights()
print(w)

[[-0.5518037  -0.59518176 -0.04212892 -0.23293227 -0.14925991 -0.738524
  -0.7478132   0.556123   -1.0937659   1.4581293  -0.13026583 -0.6222195
  -0.15964748 -0.17574191 -1.2276456  -0.66304797 -0.19037695  1.3497534
  -0.22802635 -0.41381192 -0.5349697  -0.87634736 -0.6388024  -0.87506396
   0.19538501 -0.87363935 -0.5917593  -0.05743277 -0.57516485 -0.15912387
  -1.2634215  -0.17051151 -0.4159846  -0.22718903 -0.53197455 -0.1377458
  -0.5032271  -0.33293733  1.5808572  -0.46889493 -0.4329806  -0.06525742
  -0.95620185 -0.42254055 -0.11570083  0.0293875  -0.933151   -0.51595014
   1.6579514  -0.13306099 -0.8778075  -0.21753217 -0.10413426 -0.00995937
  -0.27804834 -0.5264797  -0.01120643 -0.09220596 -0.520226   -0.492394
  -0.38925904 -0.13572076 -1.4445951  -0.54542464 -0.51310235 -0.4798108
  -0.42846802  1.6561832  -0.495389   -0.52290183  0.00763658  1.742977
  -0.04856975  0.03911554  0.01201935 -0.477343    0.4228084  -0.55149305
   0.893193   -0.02177897 -0.22244273 -0.5960444

In [44]:
model.predict(x)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


array([[2.7060165e-04],
       [9.9994367e-01],
       [9.9993938e-01],
       [4.1632662e-05]], dtype=float32)

### model 3

In [ ]:
x_train = np.array([[0,0], [0,1], [1,0], [1,1]], np.float32)
y_train = np.array([[0],[1],[1],[0]], np.float32)

myin = Input(shape=(2,))
z = Dense(units=100, activation='relu')(myin) # (myin) -> __call__ 동일
hx = Dense(units=1,  activation='sigmoid')(z)

model = Model(inputs=myin, outputs=hx)
model.compile(loss='binary_crossentropy', optimizer=Adam(0.1), metrics=['acc'])
h = model.fit(x_train, y_train, epochs=100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 323ms/step - acc: 0.7500 - loss: 0.6920
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - acc: 0.5000 - loss: 0.7910
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - acc: 0.7500 - loss: 0.6198
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.5000 - loss: 0.6112
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.7500 - loss: 0.5858
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.5376
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 1.0000 - loss: 0.4601
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 1.0000 - loss: 0.3754
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 1.0000 - loss: 0.3015
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.2445
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 1.0000 - loss: 0.1909
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.1478
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/st

### model 4 (pytorch 사용 多)

In [ ]:
# Model을 상속 받는 클래스 생성
class MyXOR(Model):
    def __init__(self):
        super(MyXOR, self).__init__() # Model 생성자 호출

        self.dense1 = Dense(units=100, activation='relu')
        self.dense2 = Dense(units=1, activation='sigmoid')

    def call(self, inputs):
        hx1 = self.dense1(inputs)
        return self.dense2(hx1)
    
model = MyXOR()
model.compile(loss='binary_crossentropy', optimizer=Adam(0.1), metrics=['acc'])
h = model.fit(x_train, y_train, epochs=100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 339ms/step - acc: 0.5000 - loss: 0.6920
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 0.5000 - loss: 0.6445
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.5000 - loss: 0.5642
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 1.0000 - loss: 0.4411
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 1.0000 - loss: 0.3602
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 1.0000 - loss: 0.2613
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.1749
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 1.0000 - loss: 0.1050
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 1.0000 - loss: 0.0648
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 1.0000 - loss: 0.0367
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 1.0000 - loss: 0.0191
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 1.0000 - loss: 0.0097
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/st

In [ ]:
model.predict(x_train) # model.call(x_train)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step


array([[1.3684763e-07],
       [9.9999022e-01],
       [9.9999982e-01],
       [6.2989902e-06]], dtype=float32)

In [51]:
### 퀴즈: iris dataset을 모델4 딥러닝으로 구성 후 예측값을 구하시오. (hidden layer 2개)

In [94]:
from sklearn.datasets import load_iris
from keras.utils import to_categorical
from sklearn.metrics import accuracy_score

iris = load_iris()
x = iris['data']
y = to_categorical(iris['target'])

In [95]:
x.shape

(150, 4)

In [96]:
y.shape

(150, 3)

In [100]:
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [97]:
# Model을 상속 받는 클래스 생성
class MyIris(Model):
    def __init__(self):
        super(MyIris, self).__init__() # Model 생성자 호출

        self.dense1 = Dense(units=32, activation='relu')
        self.dense2 = Dense(units=16, activation='relu')
        self.dense3 = Dense(units=3, activation='softmax')

    def call(self, inputs):
        hx1 = self.dense1(inputs)
        hx2 = self.dense2(hx1)
        return self.dense3(hx2)
    
model = MyIris()
model.compile(loss='categorical_crossentropy', optimizer=Adam(0.01), metrics=['acc'])
h = model.fit(x, y, epochs=500)

Epoch 1/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.3533 - loss: 1.1847  
Epoch 2/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.6533 - loss: 0.7877 
Epoch 3/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.6667 - loss: 0.6009 
Epoch 4/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.7800 - loss: 0.4681 
Epoch 5/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9333 - loss: 0.4146 
Epoch 6/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9333 - loss: 0.3588 
Epoch 7/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9667 - loss: 0.3134 
Epoch 8/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9467 - loss: 0.2786 
Epoch 9/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.2473 
Epoch 10/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9400 - loss: 0.2134 
Epoch 11/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9733 - loss: 0.1856 
Epoch 12/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9733 - loss: 0.1699 
Epoch 13/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/ste

In [98]:
pred = model.predict(x).argmax(axis=1)
# accuracy_score(y.argmax(axis=1), pred)
accuracy_score(iris['target'], pred)


5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step 


0.9866666666666667