In [1]:
import torch
from torch.optim import Adam
from torch.nn import Linear, MSELoss, Sequential
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../data/cars.csv', index_col='Unnamed: 0')
df

,speed,dist
1,4,2
2,4,10
3,7,4
4,7,22
5,8,16
6,9,10
7,10,18
8,10,26
9,10,34
10,11,17


In [3]:
x = torch.FloatTensor( df[['speed']].values )
y = torch.FloatTensor( df[['dist']].values )

In [4]:
linear = Linear( 1, 1 ) # w:1x1, b:1, hx = w*x + b
print( list( linear.parameters() )  )

[Parameter containing:
tensor([[0.6726]], requires_grad=True), Parameter containing:
tensor([-0.6219], requires_grad=True)]


In [5]:
linear( torch.FloatTensor( [[15],[20]] ) )

tensor([[ 9.4665],
        [12.8293]], grad_fn=<AddmmBackward0>)

In [6]:
linear.forward( torch.FloatTensor( [[15],[20]] ) )

tensor([[ 9.4665],
        [12.8293]], grad_fn=<AddmmBackward0>)

In [10]:
linear = Linear( 1,1)
model = Sequential()
model.add_module( 'nn1', linear )

In [12]:
list(model.parameters())

[Parameter containing:
 tensor([[3.6866]], requires_grad=True),
 Parameter containing:
 tensor([-13.3837], requires_grad=True)]

In [ ]:
loss_fn = MSELoss()
optimizer = Adam( model.parameters(),  lr=0.1)
for step in range(1000):
    optimizer.zero_grad() # 미분이 계속 누적되기 때문에 초기화 과정을 거침
    hx = model(x) # linear(x) --> w*x + b
    cost = loss_fn( hx, y ) 
    cost.backward() # dmse/dw, dmse/db
    optimizer.step() # w = w-0.1*dmse/dw , b = b-0.1*dmse/db
    print( step, cost.item() )

0 2804.74072265625
1 2634.378662109375
2 2470.1142578125
3 2312.047119140625
4 2160.26416015625
5 2014.83935546875
6 1875.8326416015625
7 1743.2884521484375
8 1617.2353515625
9 1497.6845703125
10 1384.6298828125
11 1278.045654296875
12 1177.887451171875
13 1084.0911865234375
14 996.5723266601562
15 915.2262573242188
16 839.9281005859375
17 770.533447265625
18 706.8775634765625
19 648.777587890625
20 596.031982421875
21 548.4230346679688
22 505.7171936035156
23 467.6672668457031
24 434.0140686035156
25 404.4884033203125
26 378.8134460449219
27 356.706787109375
28 337.8831787109375
29 322.0567626953125
30 308.94403076171875
31 298.2658386230469
32 289.75006103515625
33 283.1338806152344
34 278.1658020019531
35 274.6075439453125
36 272.23565673828125
37 270.8429260253906
38 270.2392272949219
39 270.25244140625
40 270.72857666015625
41 271.5321350097656
42 272.54559326171875
43 273.669189453125
44 274.81982421875
45 275.9305419921875
46 276.9488525390625
47 277.8360900878906
48 278.5654602

In [8]:
model( torch.FloatTensor( [[15],[20]] ) )

tensor([[42.2343],
        [59.8965]], grad_fn=<AddmmBackward0>)

In [9]:
model.forward( torch.FloatTensor( [[15],[20]] ) )

tensor([[42.2343],
        [59.8965]], grad_fn=<AddmmBackward0>)