In [1]:
import torch
from torch.optim import Adam
from torch.nn import Linear, MSELoss, Sequential
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv( '../data/test.csv',header=None)
df.columns = ['q1','q2','mid','final']
df

,q1,q2,mid,final
0,73,80,75,152
1,93,88,93,185
2,89,91,90,180
3,96,98,100,196
4,73,66,70,142
5,53,46,55,101
6,69,74,77,149
7,47,56,60,115
8,87,79,90,175
9,79,70,88,164


In [3]:
x_data = df.iloc[:, :-1].values
y_data = df.iloc[:, [-1]].values

In [4]:
x = torch.FloatTensor( x_data )
y = torch.FloatTensor( y_data )

In [5]:
model = Sequential()
model.add_module( 'nn1', Linear( 3,1 )) # w:3x1, b:1
loss_fn = MSELoss()
optimizer = Adam( model.parameters(), lr=0.1 )

In [6]:
for epoch in range(1000):
    optimizer.zero_grad()
    hx = model(x) # hx = torch.matmul( x, w) + b
    cost = loss_fn( hx, y )
    cost.backward()
    optimizer.step()
    print( 'cost:', cost.item())

cost: 11359.447265625
cost: 6768.91455078125
cost: 3405.662109375
cost: 1247.293701171875
cost: 199.94296264648438
cost: 65.8237533569336
cost: 534.4815063476562
cost: 1234.219970703125
cost: 1838.438720703125
cost: 2154.82275390625
cost: 2139.164794921875
cost: 1851.84033203125
cost: 1403.2806396484375
cost: 912.5875244140625
cost: 481.5985107421875
cost: 180.04931640625
cost: 38.5173225402832
cost: 48.25115203857422
cost: 168.1905059814453
cost: 338.5877380371094
cost: 498.2003173828125
cost: 599.9851684570312
cost: 620.6226196289062
cost: 561.9985961914062
cost: 445.93292236328125
cost: 305.1241455078125
cost: 173.33253479003906
cost: 77.06806182861328
cost: 30.219009399414062
cost: 32.36751937866211
cost: 70.82609558105469
cost: 125.61322021484375
cost: 175.81422424316406
cost: 205.4044189453125
cost: 206.9033203125
cost: 182.0918426513672
cost: 140.03053283691406
cost: 93.36731719970703
cost: 54.218143463134766
cost: 30.805391311645508
cost: 25.666183471679688
cost: 35.73540496826

In [7]:
list( model[0].parameters() )

[Parameter containing:
 tensor([[0.4154, 0.5189, 1.0795]], requires_grad=True),
 Parameter containing:
 tensor([0.0904], requires_grad=True)]

In [8]:
list( model.parameters() )

[Parameter containing:
 tensor([[0.4154, 0.5189, 1.0795]], requires_grad=True),
 Parameter containing:
 tensor([0.0904], requires_grad=True)]

In [9]:
model[0].weight

Parameter containing:
tensor([[0.4154, 0.5189, 1.0795]], requires_grad=True)

In [10]:
# q1:90, q2:90, mid:80 예측값을 구하시요.
model.forward( torch.FloatTensor( [[90,90,80]] ) )

tensor([[170.5314]], grad_fn=<AddmmBackward0>)

### low level

In [11]:
x_data = df.iloc[:, :-1].values
y_data = df.iloc[:, [-1]].values

In [12]:
x = torch.FloatTensor( x_data )
y = torch.FloatTensor( y_data )

In [13]:
w = torch.empty( [3,1],requires_grad=True) # [특성데이터갯수, 라벨갯수]
b = torch.empty( [1],requires_grad=True)# [라벨갯수]
torch.nn.init.uniform_(w)
torch.nn.init.uniform_(b)

tensor([0.7731], requires_grad=True)

In [14]:
def cost():
    hx = torch.matmul( x,w) +b
    c = torch.mean( (hx-y)**2 )
    return c

In [15]:
optimizer = Adam( [w,b], lr=0.01)
for epoch in range( 1000):
    c = cost()
    optimizer.zero_grad()
    c.backward()
    optimizer.step()
    print( 'cost:', c.item())

cost: 138.24365234375
cost: 89.8321762084961
cost: 53.69482421875
cost: 29.656787872314453
cost: 16.909954071044922
cost: 13.722845077514648
cost: 17.30856704711914
cost: 24.160573959350586
cost: 30.922822952270508
cost: 35.298728942871094
cost: 36.39727783203125
cost: 34.476688385009766
cost: 30.4566707611084
cost: 25.486366271972656
cost: 20.650606155395508
cost: 16.789627075195312
cost: 14.400927543640137
cost: 13.604453086853027
cost: 14.171469688415527
cost: 15.617009162902832
cost: 17.342313766479492
cost: 18.792020797729492
cost: 19.58125114440918
cost: 19.55869483947754
cost: 18.800146102905273
cost: 17.54788589477539
cost: 16.124162673950195
cost: 14.842784881591797
cost: 13.937914848327637
cost: 13.520678520202637
cost: 13.56976318359375
cost: 13.954610824584961
cost: 14.48291301727295
cost: 14.958674430847168
cost: 15.233839988708496
cost: 15.239728927612305
cost: 14.992989540100098
cost: 14.577335357666016
cost: 14.11043930053711
cost: 13.70690631866455
cost: 13.44733905792

In [16]:
def hxFn( xd ):
    xd = torch.FloatTensor( xd )
    hx = torch.matmul( xd,w ) + b
    return hx.detach().numpy()

In [17]:
hxFn( [[80,90,90]] )

array([[177.48041]], dtype=float32)