In [1]:
import torch
from torch.optim import Adam
from torch.nn import Linear, MSELoss, Sequential, CrossEntropyLoss,Softmax
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv( '../data/softmax.txt',sep=' ', header=None)
df

,0,1,2,3,4
0,2,1,0,0,1
1,3,2,0,0,1
2,3,4,0,0,1
3,5,5,0,1,0
4,7,5,0,1,0
5,2,5,0,1,0
6,6,6,1,0,0
7,7,7,1,0,0


In [3]:
x_data = df.iloc[:, 0:2]
y_data = df.iloc[:,2:]

In [4]:
x= torch.FloatTensor( x_data.values )
y= torch.FloatTensor( y_data.values )

In [5]:
s = torch.nn.Softmax()
s1 = torch.nn.Softmax(dim=1)
s2 = torch.nn.Softmax(dim=0)
rdata = torch.randn( 2,3 )
rdata

tensor([[-0.2059, -0.5536,  1.7609],
        [ 0.1839, -1.0011, -0.3786]])

In [6]:
s( rdata )

c:\Python310\lib\site-packages\torch\nn\modules\module.py:1775: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


tensor([[0.1129, 0.0798, 0.8073],
        [0.5332, 0.1630, 0.3038]])

In [7]:
s1( rdata )

tensor([[0.1129, 0.0798, 0.8073],
        [0.5332, 0.1630, 0.3038]])

In [8]:
s2( rdata )

tensor([[0.4038, 0.6100, 0.8947],
        [0.5962, 0.3900, 0.1053]])

In [9]:
model = Sequential()
model.add_module( 'nn1', Linear( 2,3)) # w:2x3, b:3
model.add_module( 'soft1', Softmax( dim=1))
loss_fn = CrossEntropyLoss()
optimizer = Adam( model.parameters(), lr= 0.01 )

In [10]:
for step in range(2000):
    optimizer.zero_grad()
    hx = model(x)  #z =matmul( x, w) + b => hx = softmax( z ) 
    cost = loss_fn( hx, y)
    cost.backward()
    optimizer.step()
    print( step, cost.item())

0 1.2774238586425781
1 1.2749545574188232
2 1.2722195386886597
3 1.269189476966858
4 1.2658333778381348
5 1.2621183395385742
6 1.2580108642578125
7 1.2534782886505127
8 1.248490333557129
9 1.2430226802825928
10 1.2370612621307373
11 1.230607509613037
12 1.2236868143081665
13 1.2163589000701904
14 1.2087302207946777
15 1.2009696960449219
16 1.1933233737945557
17 1.1861244440078735
18 1.1797828674316406
19 1.1747313737869263
20 1.1712946891784668
21 1.1694812774658203
22 1.1688212156295776
23 1.168463110923767
24 1.167544960975647
25 1.1655088663101196
26 1.1621617078781128
27 1.1575829982757568
28 1.1520180702209473
29 1.1458029747009277
30 1.1393154859542847
31 1.1329412460327148
32 1.1270487308502197
33 1.121968388557434
34 1.1179618835449219
35 1.115177869796753
36 1.113602876663208
37 1.1130406856536865
38 1.1131536960601807
39 1.1135632991790771
40 1.1139485836029053
41 1.1141002178192139
42 1.113922119140625
43 1.1134095191955566
44 1.1126221418380737
45 1.1116609573364258
46 1.11

In [11]:
model( torch.FloatTensor( [[5,6], [2,1] ]) ) 

tensor([[9.3388e-01, 2.6285e-04, 6.5856e-02],
        [1.6160e-05, 3.6092e-07, 9.9998e-01]], grad_fn=<SoftmaxBackward0>)

In [12]:
model( torch.FloatTensor( [[5,6], [2,1] ]) ).argmax(dim=1)

tensor([0, 2])