In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
import numpy as np

In [2]:
x_data = np.array( [[0,0],[0,1],[1,0],[1,1]] )
y_data = np.array( [[0],[1],[1],[0] ] )

In [3]:
model_logi = LogisticRegression( max_iter=1000, verbose=1)
model_logi.fit( x_data, y_data )

C:\Users\NT350XCR\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(max_iter=1000, verbose=1)

In [5]:
model_logi.predict( x_data )

array([0, 0, 0, 0])

In [6]:
model_logi.predict_proba( x_data )

array([[0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5]])

In [9]:
model_logi.coef_

array([[0., 0.]])

In [10]:
model_logi.intercept_

array([0.])

In [ ]:
model_mlp = MLPClassifier(max_iter=1000 ,hidden_layer_sizes=(100,) ,verbose=True )
model_mlp.fit( x_data, y_data )

In [11]:
model_mlp.predict( x_data )

array([0, 1, 1, 0])

In [18]:
model_mlp.predict_proba( x_data )

array([[0.97363365, 0.02636635],
       [0.02529071, 0.97470929],
       [0.02614076, 0.97385924],
       [0.97435678, 0.02564322]])

In [ ]:
model_mlp.coefs_

In [13]:
model_mlp.coefs_[0].shape

(2, 100)

In [14]:
model_mlp.coefs_[1].shape

(100, 1)

In [16]:
model_mlp.intercepts_[0].shape

(100,)

In [17]:
model_mlp.intercepts_[1].shape

(1,)

In [ ]:
model_mlp = MLPClassifier(max_iter=1000 ,hidden_layer_sizes=(64,32) ,verbose=True )
model_mlp.fit( x_data, y_data )

In [20]:
model_mlp.predict( x_data )

array([0, 1, 1, 0])

In [21]:
len( model_mlp.coefs_ )

3

In [22]:
model_mlp.coefs_[0].shape

(2, 64)

In [23]:
model_mlp.coefs_[1].shape

(64, 32)

In [24]:
model_mlp.coefs_[2].shape

(32, 1)