In [1]:
import tensorflow as tf
from keras.optimizers import Adam
from keras import Sequential
from keras.layers import Dense
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

In [2]:
df = pd.read_csv('../data/softmax.txt', sep=' ', header=None)
df

,0,1,2,3,4
0,2,1,0,0,1
1,3,2,0,0,1
2,3,4,0,0,1
3,5,5,0,1,0
4,7,5,0,1,0
5,2,5,0,1,0
6,6,6,1,0,0
7,7,7,1,0,0


In [3]:
x_data = df.iloc[:, :2].values.astype(np.float32) # 공부한 시간, 출석 일수
y_data = df.iloc[:, 2:].values # 학점

In [4]:
y_data

array([[0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0]])

In [5]:
y_data.shape

(8, 3)

In [6]:
dense = Dense(units=3, input_dim=2, activation='softmax') # w: 2X3 (특성데이터 갯수, 라벨의 갯수), b:[라벨의 갯수]
dense(x_data)

c:\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


<tf.Tensor: shape=(8, 3), dtype=float32, numpy=
array([[4.7676373e-02, 7.1279824e-01, 2.3952542e-01],
       [9.5408112e-03, 8.0118233e-01, 1.8927687e-01],
       [1.7667896e-03, 6.6059244e-01, 3.3764079e-01],
       [1.5264575e-04, 8.5329133e-01, 1.4655600e-01],
       [2.4294030e-05, 9.6221954e-01, 3.7756175e-02],
       [1.3096104e-03, 3.8816077e-01, 6.1052966e-01],
       [2.8417391e-05, 8.9223427e-01, 1.0773736e-01],
       [5.2267728e-06, 9.2174566e-01, 7.8249156e-02]], dtype=float32)>

In [7]:
w, b = dense.get_weights() # 학습되지 않음
print(w)
print('-'*40)
print(b)

[[-0.6096899   0.36932552 -0.36887473]
 [-0.32730907  0.41942275  0.80528426]]
----------------------------------------
[0. 0. 0.]


In [8]:
z = tf.matmul(x_data, w) + b
hx = tf.nn.softmax(z)
hx.numpy().argmax(axis=1)

array([1, 1, 1, 1, 1, 2, 1, 1])

In [9]:
w.shape

(2, 3)

In [10]:
dense = Dense(units=3, input_dim=2, activation='softmax')
model = Sequential( [dense] )
model.compile(loss='categorical_crossentropy', optimizer=Adam(0.1), metrics=['acc']) # acc : 정확도를 출력해줌
h = model.fit(x_data, y_data, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - acc: 0.3750 - loss: 2.6722
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - acc: 0.2500 - loss: 2.5122
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - acc: 0.2500 - loss: 2.0972
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - acc: 0.2500 - loss: 1.7275
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - acc: 0.3750 - loss: 1.4633
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - acc: 0.5000 - loss: 1.1939
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - acc: 0.6250 - loss: 0.9593
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 238ms/step - acc: 0.3750 - loss: 0.9575
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - acc: 0.3750 - loss: 1.2101
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - acc: 0.3750 - loss: 1.3212
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - acc: 0.3750 - loss: 1.2246
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - acc: 0.5000 - loss: 1.0446
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 1

In [11]:
w, b = dense.get_weights() # 학습된 데이터
print(w)
print('-'*40)
print(b)

[[-0.12174691 -0.21917146 -0.47657374]
 [ 3.2843401   0.68049604 -1.7353053 ]]
----------------------------------------
[-15.444616    -0.12660323  10.93695   ]


In [12]:
dense(x_data).numpy().argmax(axis=1)

array([2, 2, 2, 1, 1, 1, 0, 0])

In [13]:
y_data.argmax(axis=1)

array([2, 2, 2, 1, 1, 1, 0, 0])

In [14]:
model.predict(x_data).argmax(axis=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step


array([2, 2, 2, 1, 1, 1, 0, 0])

## iris 데이터 셋 케라스로 학습하고
## 1,2 번째 행의 예측값을 구하시오.

In [15]:
from keras.utils import to_categorical

In [16]:
from sklearn.datasets import load_iris

In [17]:
iris = load_iris(as_frame=True)
iris['frame']

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2


In [18]:
xdata = iris['data'].values
ydata = to_categorical(iris['target'])

In [19]:
xdata.shape

(150, 4)

In [20]:
ydata

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [21]:
ydata.shape

(150, 3)

In [22]:
dense = Dense(units=3, input_dim=4, activation='softmax') # w: 2X3 (특성데이터 갯수, 라벨의 갯수), b:[라벨의 갯수]
dense(xdata)

c:\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


<tf.Tensor: shape=(150, 3), dtype=float32, numpy=
array([[9.99896407e-01, 9.88888205e-05, 4.61679792e-06],
       [9.99728024e-01, 2.59589026e-04, 1.23626569e-05],
       [9.99776781e-01, 2.10801009e-04, 1.24099915e-05],
       [9.99734461e-01, 2.51808699e-04, 1.36470935e-05],
       [9.99907494e-01, 8.80441512e-05, 4.43410272e-06],
       [9.99962926e-01, 3.57863973e-05, 1.30366391e-06],
       [9.99843717e-01, 1.47242594e-04, 9.09992468e-06],
       [9.99873519e-01, 1.21010075e-04, 5.52505207e-06],
       [9.99569595e-01, 4.05296334e-04, 2.51845795e-05],
       [9.99765933e-01, 2.23964147e-04, 1.00844109e-05],
       [9.99939561e-01, 5.81488930e-05, 2.23666598e-06],
       [9.99861836e-01, 1.31840716e-04, 6.35033575e-06],
       [9.99698162e-01, 2.87587434e-04, 1.42910158e-05],
       [9.99561012e-01, 4.06788342e-04, 3.22194937e-05],
       [9.99968767e-01, 3.00365318e-05, 1.16682384e-06],
       [9.99985933e-01, 1.35394812e-05, 5.15438217e-07],
       [9.99958754e-01, 3.94084527e-05

In [23]:
w, b = dense.get_weights() # 학습되지 않음
print(w)
print('-'*40)
print(b)

[[ 0.4476303  -0.10155076 -0.67124176]
 [ 0.8930477  -0.8178235  -0.6296972 ]
 [-0.07882035 -0.31986266 -0.924294  ]
 [ 0.6552075   0.17981398  0.32426846]]
----------------------------------------
[0. 0. 0.]


In [24]:
z = tf.matmul(xdata, w) + b
hx = tf.nn.softmax(z)
hx.numpy().argmax(axis=1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
dense = Dense(units=3, input_dim=4, activation='softmax') # units= y, input_dim= x
model = Sequential( [dense] )
model.compile(loss='categorical_crossentropy', optimizer=Adam(0.1), metrics=['acc']) # acc : 정확도를 출력해줌
h = model.fit(xdata, ydata, epochs=500)

Epoch 1/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.3400 - loss: 4.5143 
Epoch 2/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.3933 - loss: 1.9383 
Epoch 3/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.4600 - loss: 1.9720
Epoch 4/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.4400 - loss: 1.0017
Epoch 5/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.4800 - loss: 0.8326
Epoch 6/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.6200 - loss: 0.6256
Epoch 7/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.8067 - loss: 0.4696 
Epoch 8/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.8400 - loss: 0.4709
Epoch 9/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.7800 - loss: 0.4289 
Epoch 10/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9067 - loss: 0.3889 
Epoch 11/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.8000 - loss: 0.3722
Epoch 12/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9067 - loss: 0.3556
Epoch 13/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms

In [26]:
model.predict(xdata[[0,1]]).argmax(axis=1) # 2X4 4X3

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step


array([0, 0])