## 과제 (low, high-> 케라스)
- 피마인디안 데이터셋 이용
- train, test 나누기
- 정규화
- 딥러닝
- train, test 정확도, f1, confusion matrix
- train 1,2 예측값

In [108]:
import tensorflow as tf
from keras.optimizers import Adam
from keras import Sequential, Model
from keras.layers import Dense, Input
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sb
from scikeras.wrappers import KerasClassifier, KerasRegressor # 분류 KerasClassifier , 회귀(연속값) KerasRegressor
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score

import matplotlib
matplotlib.rcParams['font.family']='Malgun Gothic'
matplotlib.rcParams['axes.unicode_minus'] = False

In [109]:
df = pd.read_csv('../../data/pima-indians-diabetes.data.csv')
df.head(3)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1


In [110]:
x_data = df.iloc[:,:-1]
y_data = df.iloc[:, -1]

In [111]:
x_data.shape

(768, 8)

In [112]:
y_data

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [113]:
y_data.shape

(768,)

---

train, test 나누기

In [114]:
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42, stratify=y_data)

---

정규화

In [115]:
scaler = StandardScaler()
x_train_s = scaler.fit_transform(x_train)
x_test_s = scaler.transform(x_test)

In [116]:
x_train_s.shape

(614, 8)

In [117]:
y_train.shape

(614,)

---

딥러닝 및 파이프라인

In [ ]:
# dense 두번으로 줄이고 4X1 , 반복 30회로 줄이기
def get_model():
    myin = Input(shape=(8,))
    dense1 = Dense(units=32, activation='relu')
    dense2 = Dense(units=16, activation='relu')
    dense3 = Dense(units=1, activation='sigmoid')
    model = Sequential([myin, dense1, dense2, dense3])
    model.compile(loss='binary_crossentropy', metrics=['acc'])
    return model

In [119]:
mode_sci = KerasClassifier(model=get_model, epochs=500) # 학습 시 주는 인자는 KerasClassifier() 안에 넣어 주기
pipe = Pipeline([('scaler', StandardScaler()),
                ('keras', mode_sci)])
pipe.fit(x_train_s, y_train)

Epoch 1/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - acc: 0.6107 - loss: 0.6796
Epoch 2/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - acc: 0.6938 - loss: 0.6102
Epoch 3/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - acc: 0.7231 - loss: 0.5647
Epoch 4/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.7476 - loss: 0.5295 
Epoch 5/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - acc: 0.7622 - loss: 0.5033
Epoch 6/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - acc: 0.7736 - loss: 0.4849
Epoch 7/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.7769 - loss: 0.4732 
Epoch 8/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - acc: 0.7785 - loss: 0.4646 
Epoch 9/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - acc: 0.7850 - loss: 0.4584 
Epoch 10/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.7866 - loss: 0.4537 
Epoch 11/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.7866 - loss: 0.4500 
Epoch 12/500
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - acc: 0.7866 - loss: 0.4468 
Epoch 13/500
20/20 ━

,steps,"[('scaler', ...), ('keras', ...)]"
,transform_input,None
,memory,None
,verbose,False
,copy,True
,with_mean,True
,with_std,True
,model,<function get...0024B31C164D0>
,build_fn,None
,warm_start,False
,random_state,None


In [120]:
pred_tr = (pipe.predict(x_train_s) > 0.5) + 0
pred_tr

20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


array([0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,

In [121]:
pred_ts = (pipe.predict(x_test_s) > 0.5) + 0
pred_ts

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 


array([1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0])

---

accuracy_score, f1_score

In [122]:
print('accuracy_score(Train)',accuracy_score(y_train, pred_tr))
print('accuracy_score(Test)',accuracy_score(y_test, pred_ts))

accuracy_score(Train) 0.9853420195439739
accuracy_score(Test) 0.6753246753246753


In [123]:
print('f1_score(Train)',f1_score(y_train, pred_tr))
print('f1_score(Test)',f1_score(y_test, pred_ts))

f1_score(Train) 0.9787234042553191
f1_score(Test) 0.5535714285714286


---

confusion_matrix

In [128]:
c_tr = confusion_matrix(y_train, pred_tr)
c_tr


array([[398,   2],
       [  7, 207]])

In [129]:
c_ts = confusion_matrix(y_test, pred_ts)
c_ts

array([[73, 27],
       [23, 31]])

---

train 1,2 예측값

In [126]:
y_pred_tr = pipe.predict(x_train_s)

print(y_pred_tr[:2])

20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 
[0 0]
