In [2]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression, SGDRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.pipeline import make_pipeline, Pipeline


import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['font.family'] = 'Malgun Gothic'
matplotlib.rcParams['axes.unicode_minus'] = False


In [3]:
data = [[828, 920, 1234567, 1020, 1111],
            [824, 910, 2345612, 1090, 1234],
            [880, 900, 3456123, 1010, 1000],
            [870, 990, 2312123, 1001, 1122],
            [860, 980, 3223123, 1008, 1133],
            [850, 970, 2432123, 1100, 1221]]
data = np.float32(data)

df = pd.DataFrame( data )
df

,0,1,2,3,4
0,828.0,920.0,1234567.0,1020.0,1111.0
1,824.0,910.0,2345612.0,1090.0,1234.0
2,880.0,900.0,3456123.0,1010.0,1000.0
3,870.0,990.0,2312123.0,1001.0,1122.0
4,860.0,980.0,3223123.0,1008.0,1133.0
5,850.0,970.0,2432123.0,1100.0,1221.0


In [4]:
x_data = df.iloc[:, :-1].values
y_data = df.iloc[:, -1].values

In [5]:
model_pipeline = make_pipeline(MinMaxScaler(), SGDRegressor(max_iter=200))
print(model_pipeline)

Pipeline(steps=[('minmaxscaler', MinMaxScaler()),
                ('sgdregressor', SGDRegressor(max_iter=200))])


In [6]:
model_pipeline.fit(x_data,y_data) # 스케일링을 통과 후 MinMax -> SDGReress 단계 

c:\Python310\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:1579: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


,steps,"[('minmaxscaler', ...), ('sgdregressor', ...)]"
,transform_input,None
,memory,None
,verbose,False
,feature_range,"(0, ...)"
,copy,True
,clip,False
,loss,'squared_error'
,penalty,'l2'
,alpha,0.0001
,l1_ratio,0.15


In [7]:
# 데이터 역정규화 후 모델에게 전달
model_pipeline.predict([[828, 920, 1234567, 1020]])

array([764.60936411])

In [8]:
model_reg = model_pipeline.named_steps['sgdregressor'] # named_steps으로 이름을 주면 SGDRegressor 객체를 따로 얻어 올 수 있음
print(model_reg.coef_)
print(model_reg.intercept_)

[174.81007 239.07755 243.82214 283.14008]
[644.65446842]


In [9]:
df = pd.read_csv('data/pima-indians-diabetes.data.csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1


In [10]:
x_data = df.iloc[:, :-1].values
y_data = df.iloc[:, -1].values

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, 
                                                    test_size=0.3, stratify=y_data)

In [ ]:
model_pipe = Pipeline([('scaler', StandardScaler()),
                    ('regress',LogisticRegression(max_iter=500))]) # Pipeline은 각 단계를 ('이름', 객체) 형태의 튜플로 정의하며, 이 튜플들을 리스트로 나열해 구성해야 한다.
model_pipe.fit(x_train, y_train) # 전처리 단계(스케일링)를 먼저 두고, 그 다음 모델(LogisticRegression)을 둔다.

,steps,"[('scaler', ...), ('regress', ...)]"
,transform_input,None
,memory,None
,verbose,False
,copy,True
,with_mean,True
,with_std,True
,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0


In [12]:
model_pipe.predict([[6, 148, 72, 35, 0, 33.6, 0.627, 50]]) # 파이프 라인을 이용하면 정규화 후 학습해 줌

array([1])

In [13]:
model_logi = model_pipe.named_steps['regress']
print(model_logi.coef_)
print(model_logi.intercept_)

[[ 0.37921512  1.15331593 -0.16575057  0.03075728 -0.08786259  0.64626555
   0.26662186  0.15483751]]
[-0.87294866]
