##  선형대수학 

선형대수학(**Linear Algebra**)은 **벡터(Vector)**, **행렬(Matrix)**, 그리고 이들을 이용한 **선형 변환(Linear Transformation)**을 다루는 수학 분야입니다. 

---

### 1. 주요 구성 요소

| 요소 | 간단 정의 | 핵심 역할 |
| :--- | :--- | :--- |
| **벡터 (Vector)** | 크기와 방향을 가진 물리량. 숫자를 일렬로 나열한 것. | 공간에서의 **점**이나 **방향**을 나타내며, 데이터 과학에서 **데이터의 한 단위**를 표현합니다. |
| **행렬 (Matrix)** | 숫자를 직사각형 모양으로 배열한 것. (행과 열) | **선형 변환** 자체를 나타내거나, **연립 선형 방정식**의 계수를 저장하는 데 사용됩니다. 데이터를 효율적으로 저장하고 처리합니다. |
| **스칼라 (Scalar)** | 크기만 있는 단순한 수. | 벡터나 행렬의 **크기를 조절**하거나, **배율**을 나타냅니다. |

---

### 2. 핵심 개념 및 연산

* **선형 결합 (Linear Combination):** 여러 벡터를 스칼라로 곱한 후 더하는 연산($c_1\mathbf{v}_1 + c_2\mathbf{v}_2 + \dots$)입니다. 선형대수학의 **가장 기본이 되는 연산**입니다.
* **행렬 곱셈 (Matrix Multiplication):** 여러 선형 변환을 **순차적으로 적용**하는 것을 의미합니다. 행렬 곱셈은 **교환법칙이 성립하지 않습니다**($AB \neq BA$).
* **고유값 및 고유 벡터 (Eigenvalue & Eigenvector):** 선형 변환을 적용해도 **방향이 변하지 않고 크기만 변하는** 특별한 벡터(고유 벡터)와 그 변화 비율(고유값)을 찾는 개념입니다. **데이터 분석(PCA)**에 핵심적으로 사용됩니다.
* **선형 변환 (Linear Transformation):** 벡터를 다른 벡터로 변환시키는 규칙으로, 기하학적으로 **회전, 확대/축소, 반사** 등을 나타냅니다. 모든 행렬은 선형 변환을 나타냅니다.

---

### 3. 주요 응용 분야

선형대수학은 다음과 같은 분야에서 필수적으로 사용됩니다.

* **컴퓨터 공학/그래픽스:** 3D 객체의 **변환(이동, 회전, 확대)** 및 투영 계산.
* **데이터 과학/머신러닝:** 데이터셋을 행렬로 다루고, 알고리즘(예: 회귀 분석, 신경망)에서 **가중치(Weight)**를 행렬로 표현하여 처리합니다.
* **물리학:** 양자 역학 등 복잡한 시스템의 상태와 변환을 행렬로 표현.

---

요약하자면, 선형대수학은 **복잡한 문제를 벡터와 행렬로 단순하게 표현하고, 체계적인 규칙(선형성)을 이용해 해결하는** 도구입니다.

##  행렬 곱셈 예제

주어진 행렬은 다음과 같습니다.
$$A = \begin{bmatrix} 1 & 3 \\ 5 & 7 \end{bmatrix}, \quad B = \begin{bmatrix} 1 & 2 \\ 2 & 5 \end{bmatrix}$$

---

### **1. $AB$ 계산**

$$AB = \begin{bmatrix} 1 & 3 \\ 5 & 7 \end{bmatrix} \begin{bmatrix} 1 & 2 \\ 2 & 5 \end{bmatrix} = \begin{bmatrix} (1 \cdot 1 + 3 \cdot 2) & (1 \cdot 2 + 3 \cdot 5) \\ (5 \cdot 1 + 7 \cdot 2) & (5 \cdot 2 + 7 \cdot 5) \end{bmatrix} = \begin{bmatrix} 7 & 17 \\ 19 & 45 \end{bmatrix}$$

| 계산 요소 | $\text{첫 번째 열 (}1, 2\text{)}$ | $\text{두 번째 열 (}2, 5\text{)}$ | 결과 행렬 $AB$ |
| :---: | :---: | :---: | :---: |
| $\text{첫 번째 행 (}1, 3\text{)}$ | $1\cdot 1 + 3\cdot 2 = **7**$ | $1\cdot 2 + 3\cdot 5 = **17**$ | $\begin{bmatrix} 7 & 17 \\ \end{bmatrix}$ |
| $\text{두 번째 행 (}5, 7\text{)}$ | $5\cdot 1 + 7\cdot 2 = **19**$ | $5\cdot 2 + 7\cdot 5 = **45**$ | $\begin{bmatrix} \\ 19 & 45 \end{bmatrix}$ |

$$AB = \begin{bmatrix} 7 & 17 \\ 19 & 45 \end{bmatrix}$$

---

### **2. $BA$ 계산**

$$BA = \begin{bmatrix} 1 & 2 \\ 2 & 5 \end{bmatrix} \begin{bmatrix} 1 & 3 \\ 5 & 7 \end{bmatrix} = \begin{bmatrix} (1 \cdot 1 + 2 \cdot 5) & (1 \cdot 3 + 2 \cdot 7) \\ (2 \cdot 1 + 5 \cdot 5) & (2 \cdot 3 + 5 \cdot 7) \end{bmatrix} = \begin{bmatrix} 11 & 17 \\ 27 & 41 \end{bmatrix}$$

| 계산 요소 | $\text{첫 번째 열 (}1, 5\text{)}$ | $\text{두 번째 열 (}3, 7\text{)}$ | 결과 행렬 $BA$ |
| :---: | :---: | :---: | :---: |
| $\text{첫 번째 행 (}1, 2\text{)}$ | $1\cdot 1 + 2\cdot 5 = **11**$ | $1\cdot 3 + 2\cdot 7 = **17**$ | $\begin{bmatrix} 11 & 17 \\ \end{bmatrix}$ |
| $\text{두 번째 행 (}2, 5\text{)}$ | $2\cdot 1 + 5\cdot 5 = **27**$ | $2\cdot 3 + 5\cdot 7 = **41**$ | $\begin{bmatrix} \\ 27 & 41 \end{bmatrix}$ |

$$BA = \begin{bmatrix} 11 & 17 \\ 27 & 41 \end{bmatrix}$$

---


##  행렬 곱셈의 조건 및 결과

행렬 곱셈이 가능하려면 **앞 행렬의 열의 개수**와 **뒤 행렬의 행의 개수**가 같아야 합니다.

---

### **1. 행렬 곱셈이 되는 경우**

| 구분 | 행렬의 크기 | 조건 확인 | 곱셈 결과 |
| :---: | :---: | :---: | :---: |
| **앞 행렬** | $7 \times 5$ 행렬 | **열의 개수:** 5 | $7 \times 3$ 행렬 |
| **뒤 행렬** | $5 \times 3$ 행렬 | **행의 개수:** 5 | |
| **결론** | | $5 = 5$ 이므로 **곱셈 가능** | |

> 두 행렬 $A$($m \times n$)와 $B$($n \times p$)의 곱 $AB$는 $m \times p$ 행렬이 됩니다.
> $\text{예시}: (7 \times 5) \times (5 \times 3) \rightarrow 7 \times 3$ 행렬

---

### **2. 행렬 곱셈이 되지 않는 경우**

| 구분 | 행렬의 크기 | 조건 확인 | 곱셈 결과 |
| :---: | :---: | :---: | :---: |
| **앞 행렬** | $7 \times 3$ 행렬 | **열의 개수:** 3 | **곱셈 불가능** |
| **뒤 행렬** | $5 \times 3$ 행렬 | **행의 개수:** 5 | |
| **결론** | | $3 \neq 5$ 이므로 **곱셈 불가능** | |

> 앞 행렬의 열 개수(3)와 뒤 행렬의 행 개수(5)가 다르기 때문에 행렬 곱셈을 할 수 없습니다.

---

In [2]:
import numpy as np

In [3]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [4]:
b = np.array([[1,2,3],[3,4,5]])
b

array([[1, 2, 3],
       [3, 4, 5]])

In [5]:
np.matmul(a,b)

array([[ 7, 10, 13],
       [15, 22, 29]])

In [6]:
a@b

array([[ 7, 10, 13],
       [15, 22, 29]])