정규화는 데이터의 스케일을 조정하여 모델 학습 시 안정성과 성능을 높이는 데 사용.

---

##  scikit-learn (sklearn) 정규화 종류와 공식

### 1. Min-Max Scaling (최소-최대 스케일링)

특성(feature) 값을 0과 1 사이의 범위로 변환합니다. 데이터의 분포는 유지되지만, 이상치(Outlier)에 민감합니다.

* **sklearn 클래스:** `sklearn.preprocessing.MinMaxScaler`
* **공식:**

    $$X_{\text{norm}} = \frac{X - X_{\text{min}}}{X_{\text{max}} - X_{\text{min}}}$$

    * $X$: 원본 데이터 포인트
    * $X_{\text{min}}$: 특성의 **최솟값**
    * $X_{\text{max}}$: 특성의 **최댓값**
    * $X_{\text{norm}}$: 정규화된 값

### 2. Standard Scaling (표준화)

데이터의 평균을 0, 표준편차를 1로 조정합니다. 정규 분포(Gaussian distribution)를 따르는 데이터에 특히 유용하며, 이상치의 영향을 덜 받습니다. 이는 정규화(Normalization)보다는 **표준화(Standardization)**라고 부르는 것이 더 정확합니다.

* **sklearn 클래스:** `sklearn.preprocessing.StandardScaler`
* **공식:**

    $$z = \frac{X - \mu}{\sigma}$$

    * $X$: 원본 데이터 포인트
    * $\mu$: 특성의 **평균** (Mean)
    * $\sigma$: 특성의 **표준 편차** (Standard Deviation)
    * $z$: 표준화된 값 (Z-score)

### 3. Robust Scaling (로버스트 스케일링)

중앙값(Median)과 사분위 범위(Interquartile Range, IQR)를 사용하여 스케일링합니다. Min-Max Scaling이나 Standard Scaling보다 **이상치에 훨씬 덜 민감**합니다.

* **sklearn 클래스:** `sklearn.preprocessing.RobustScaler`
* **공식:**

    $$X_{\text{robust}} = \frac{X - Q_2}{Q_3 - Q_1}$$

    * $X$: 원본 데이터 포인트
    * $Q_1$: 특성의 **1사분위 수** (25th percentile)
    * $Q_2$: 특성의 **중앙값** (Median, 50th percentile)
    * $Q_3$: 특성의 **3사분위 수** (75th percentile)
    * $Q_3 - Q_1$: 사분위 범위 (IQR)
    * $X_{\text{robust}}$: 로버스트 스케일링된 값

### 4. Normalizer (L2 정규화)

**데이터의 개별 행(샘플)**에 대해 적용되며, 각 샘플의 벡터 길이를 1로 만듭니다. 주로 텍스트 분석이나 군집화(Clustering)에서 유클리드 거리(Euclidean distance) 기반의 유사도를 측정할 때 유용합니다.

* **sklearn 클래스:** `sklearn.preprocessing.Normalizer`
* **공식 (L2 Norm):**

    $$X_{\text{norm}} = \frac{X}{\|X\|_2}$$

    여기서 $\|X\|_2$는 L2 노름(Euclidean norm)이며 다음과 같습니다:

    $$\|X\|_2 = \sqrt{\sum_{i=1}^{n} x_i^2}$$

    * $X$: 원본 데이터 샘플 (벡터)
    * $x_i$: 벡터 $X$의 $i$번째 원소
    * $\|X\|_2$: L2 노름 (벡터의 길이)
    * $X_{\text{norm}}$: 정규화된 벡터

---

### 📚 요약 표

| 정규화/표준화 기법 | Scikit-learn 클래스 | 사용되는 통계량 | 주요 특징 |
| :--- | :--- | :--- | :--- |
| **Min-Max Scaling** | `MinMaxScaler` | $\text{Min}, \text{Max}$ | 데이터 범위를 $[0, 1]$로 조정. 이상치에 민감. |
| **Standard Scaling** | `StandardScaler` | $\mu$ (평균), $\sigma$ (표준편차) | 평균 $0$, 표준편차 $1$로 조정. 이상치의 영향 적음. |
| **Robust Scaling** | `RobustScaler` | $Q_2$ (중앙값), $IQR$ ($Q_3 - Q_1$) | 이상치에 **매우 강함**. |
| **Normalizer (L2)** | `Normalizer` | L2 Norm ($\|X\|_2$) | 개별 샘플(행)의 벡터 길이를 $1$로 조정. |

---

In [5]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.datasets import load_breast_cancer
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['font.family']='Malgun Gothic'
matplotlib.rcParams['axes.unicode_minus'] = False

In [6]:
import numpy as np
import pandas as pd

data = [[828, 920, 1234567, 1020, 1111],
            [824, 910, 2345612, 1090, 1234],
            [880, 900, 3456123, 1010, 1000],
            [870, 990, 2312123, 1001, 1122],
            [860, 980, 3223123, 1008, 1133],
            [850, 970, 2432123, 1100, 1221]]
data = np.float32(data)

df = pd.DataFrame( data )
df

,0,1,2,3,4
0,828.0,920.0,1234567.0,1020.0,1111.0
1,824.0,910.0,2345612.0,1090.0,1234.0
2,880.0,900.0,3456123.0,1010.0,1000.0
3,870.0,990.0,2312123.0,1001.0,1122.0
4,860.0,980.0,3223123.0,1008.0,1133.0
5,850.0,970.0,2432123.0,1100.0,1221.0


In [7]:
x_data = df.iloc[:, :-1].values
y_data = df.iloc[:, [-1]].values

In [8]:
scaleF = MinMaxScaler()
x_dataN = scaleF.fit_transform(x_data)
x_dataN

array([[0.0714283 , 0.22222233, 0.        , 0.19191933],
       [0.        , 0.11111164, 0.50012016, 0.89899063],
       [1.        , 0.        , 1.        , 0.09090996],
       [0.8214283 , 1.        , 0.48504567, 0.        ],
       [0.6428566 , 0.8888893 , 0.8951186 , 0.07070732],
       [0.4642849 , 0.7777777 , 0.5390618 , 1.        ]], dtype=float32)

In [9]:
scaleL = MinMaxScaler() # 값이 0~1 사이
y_dataN = scaleL.fit_transform(y_data)
y_dataN

array([[0.47435904],
       [1.0000005 ],
       [0.        ],
       [0.52136755],
       [0.56837654],
       [0.94444466]], dtype=float32)

In [10]:
model = SGDRegressor(verbose=True, max_iter=200 )
model.fit(x_dataN,y_dataN)

NameError: name 'SGDRegressor' is not defined

In [ ]:
# 828, 920, 1234567, 1020 #정규화 X, 정규화 후 사용
xN =  scaleF.transform([[828, 920, 1234567, 1020]]) 
pred = model.predict(xN)
pred

array([0.29990337])

In [ ]:
scaleL.inverse_transform([pred]) # 스케일링을 해 줬기때문에 inverse_transform를 통해 역정규화를 해 줘야함

array([[1070.17733108]])

data =    [ [828, 920, 1234567, 1020, 1111],
            [824, 910, 2345612, 1090, 1234],
            [880, 900, 3456123, 1010, 1000],
            [870, 990, 2312123, 1001, 1122],
            [860, 980, 3223123, 1008, 1133],
            [850, 970, 2432123, 1100, 1221] ]