In [1]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

### 용어 정리
- scalar : 10, 3.14 'abc' # 데이터 하나를 의미
- vector(1차원): [10,20,30] , [1.1, 2.2, 3.3], ['aa','bb','cc'] # 문자열을 모아둔 것을 의미
- matrix(2차원): [[10,20,30] , [40,50,60]]  #2X3(2행 3열) #vector 여러개를 묶어둔 것을 의미
- 3차원: [ [ [10,20,30] , [40,50,60] ],[ [10,20,30] , [40,50,60] ] ] # 2X2X3 -> 2면2행3열  
- 4차원: 
[ [ [ [10,20,30] , [40,50,60] ],[ [10,20,30] , [40,50,60] ] ] ],  
[ [ [ [10,20,30] , [40,50,60] ],[ [10,20,30] , [40,50,60] ] ] ]
# 2X2X2X3 

### 1. ndarray 생성 방법

In [6]:
mylist = [10,20,30]
print(mylist)

[10, 20, 30]


In [8]:
arr = np.array([10,20,30])
print(type(arr))
print(arr)
arr ## jupyter 자체 스타일이 적용되어 출력됨

<class 'numpy.ndarray'>
[10 20 30]


array([10, 20, 30])

In [9]:
arr1 = np.array(([10,20,30],[40,50,60]))
arr1

array([[10, 20, 30],
       [40, 50, 60]])

### 2. arange
-  arange( 시작값, 끝값, 증가치)
- 시작값<=arr< 끝값

In [10]:
arr = np.arange(1,6,1)
arr

array([1, 2, 3, 4, 5])

In [12]:
np.arange(1,6,2) # 1<=arr<6 2씩 증가

array([1, 3, 5])

In [13]:
for n in np.arange(1,6):
    print(n)

1
2
3
4
5


### 3. one, zero, eye

In [15]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((3,2), dtype=np.int32)

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.eye(3) #대각선이 1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 4. linspace
https://numpy.org/doc/2.3/reference/generated/numpy.linspace.html

In [ ]:
np.linspace(1, 100, num=10) #start, stop, num=50

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

### 5. 특정 타입의 array

In [27]:
import sys
a = 10
sys.getsizeof(a)

28

In [26]:
np.int8([1,2,3,4,5])

array([1, 2, 3, 4, 5], dtype=int8)

In [ ]:
np.int16([1,2,3,4,5])
# np.array([10,20,30], dtype=np.int16)

array([1, 2, 3, 4, 5], dtype=int16)

In [29]:
np.int32([1,2,3,4,5])

array([1, 2, 3, 4, 5], dtype=int32)

In [ ]:
np.int64([1,2,3,4,5]) #64바이트가 기본 값

array([1, 2, 3, 4, 5])

In [31]:
np.array([10,20,30], dtype=np.int64)

array([10, 20, 30])

In [ ]:
np.float32([1,2,3,4,5])
# np.array([10,20,30], dtype=np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [34]:
np.str_([1,2,3,4,5]) #문자열

np.str_('[1, 2, 3, 4, 5]')

### 6.  random  <- 딥러닝, 머신러닝 파트에서 주로 사용하게 됨

In [ ]:
np.random.randint(1,10,5) # 1<=r<10 1~9까지의 숫자를 랜덤하게 array를 만들어줌

array([6, 2, 4, 2, 9], dtype=int32)

In [ ]:
np.random.randint(1,10,(2,3)) #2행3열짜리로 랜덤하게 만들어줌

array([[5, 8, 4],
       [2, 5, 6]], dtype=int32)

In [43]:
np.random.randn(5) #표준 정규분포(평균0 , 편차1) 

array([-1.0118531 , -1.52044066,  0.25158347,  0.924452  ,  0.37680459])

In [46]:
arr = np.arange(1,11)
np.random.shuffle(arr) # 중복 제거 시 suffle 사용
arr[:5]

array([ 2, 10,  7,  4,  5])

In [ ]:
np.random.seed(10) #seed: 랜덤하게 생성되는 값이 고정되어 동일하게 출력됨
np.random.randint(1,10,5)

array([5, 1, 2, 1, 2], dtype=int32)