In [1]:
import numpy as np

https://numpy.org/devdocs/reference/generated/numpy.ndarray.html

In [2]:
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

In [3]:
arr.dtype # 타입정보

dtype('int64')

In [4]:
arr.size # 데이터 총 갯수

5

In [5]:
arr.shape # 1차원:(갯수,) 2차원:(행,열) 3차원:(면,행,열)  사용 빈도 多

(5,)

In [6]:
arr.ndim # 몇 차원인가?

1

In [7]:
arr1 = np.array( [[1,2,3],[4,5,6]] )
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr1.dtype

dtype('int64')

In [9]:
arr1.size

6

In [10]:
arr1.shape

(2, 3)

In [11]:
arr1.ndim

2

In [12]:
arr1.T # 행이 열로 바뀜 transposed

array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

## reshape 함수 (사용 빈도 多)

In [14]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [15]:
arr.reshape(2,3) #동일한 데이터를 유지한 채, 새로운 형태(모양)의 배열을 반환

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr.reshape(2,-1) #(2행, 알아서)

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr.reshape(-1,2) #(알아서, 2열)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
arr1 = np.array( [[1,2,3],[4,5,6]] )
arr1.reshape(-1) 
# arr1.reshape(6) 


array([1, 2, 3, 4, 5, 6])