In [1]:
import numpy as np

In [2]:
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

## 인덱싱
- 0,1,2,3,....
- ...,-3,-2,-1

In [4]:
arr[0]

np.int64(11)

In [5]:
arr[-1]

np.int64(55)

### 복수개 인덱싱
[[인덱스번호,...]]

In [ ]:
arr[[1,4]] #1인덱스. 4인덱스 추출

array([22, 55])

In [8]:
arr

array([11, 22, 33, 44, 55])

In [ ]:
arr[[-1,-3]]
# arr[[4,2]]

array([55, 33])

### boolean indexing
- 데이터의 갯수 만큼 나열해 준다.
-[[True,False,...]] 
#데이터 필터링에 유용

In [ ]:
arr[[True,False,False,True,True]] #True 값만 출력

array([11, 44, 55])

In [15]:
arr

array([11, 22, 33, 44, 55])

## 슬라이싱
- [시작인덱스:끝인덱스:증가치]
- 시작인덱스 <= index < 끝인덱스

In [18]:
arr[1:4:1]

array([22, 33, 44])

In [19]:
arr

array([11, 22, 33, 44, 55])

In [ ]:
arr[1:4:2] #1,3

array([22, 44])

In [21]:
arr[1:4]

array([22, 33, 44])

In [22]:
arr[:4]

array([11, 22, 33, 44])

In [24]:
arr[:-1] #0<=idx<-1

array([11, 22, 33, 44])

In [ ]:
arr[::-1] #-1,-2,...

array([55, 44, 33, 22, 11])