In [ ]:
my = [11,22,33,44,55]
print(my*2) #*n 만큼 반복
print(my+[66,77])

[11, 22, 33, 44, 55, 11, 22, 33, 44, 55]
[11, 22, 33, 44, 55, 66, 77]


## 넘파이 연산(산관논 연산자 사용 가능)
- element wise : 요소별 연산(동일한 인덱스 끼리 연산)
- broad casting : 차원이 높은 쪽으로 자동 확장 

In [6]:
import numpy as np
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

In [8]:
arr+2 #[11,22,33,44,55] + [2,2,2,2,2] = [13, 24, 35, 46, 57] 벡터로 확장되어 동일한 인덱스끼리 연산됨

array([13, 24, 35, 46, 57])

In [ ]:
arr*2  #[11,22,33,44,55] * [2,2,2,2,2] = [ 22,  44,  66,  88, 110] 벡터로 확장되어 동일한 인덱스끼리 연산됨

array([ 22,  44,  66,  88, 110])

In [ ]:
arr+[1,2,3,4,5] # [11,22,33,44,55] + [1,2,3,4,5]

array([12, 24, 36, 48, 60])

In [12]:
### 퀴즈: 세금 3.3%를 제외한 실수령액을 구하시오.
salary = np.array([1000,2000,3000,4000,5000])
salary

array([1000, 2000, 3000, 4000, 5000])

In [13]:
salary*(1-0.033)

array([ 967., 1934., 2901., 3868., 4835.])

### 관계 연산자

In [16]:
arr>30 # [11,22,33,44,55] > [30,30,30,30,30]

array([False, False,  True,  True,  True])

In [18]:
mylist = [11,22,33,44,55]
[n for n in mylist if n>30]

[33, 44, 55]

In [ ]:
arr[arr>30] ##arr[[False, False,  True,  True,  True]] -> boolean indexing이 적용되어 True 값인 [33, 44, 55]이 출력

array([33, 44, 55])

In [21]:
arr<=20 #[11,22,33,44,55] <= [20,20,20,20,20]

array([ True, False, False, False, False])

In [ ]:
arr[arr<=20] #arr[[ True, False, False, False, False]] -> True 값만 출력

array([11])

### 논리 연산자
- and: &  -> 둘다 True인 경우만 True
- or: | -> 둘중 하나만 True인 경우도 True
- not: ~

(arr==22) | (arr==44)
1. step: borad casting
([11,22,33,44,55] == [22,22,22,22,22]) |
([11,22,33,44,55] == [44,44,44,44,44])
2. element wise
([F,T,F,F,F]) | ([F,F,F,T,F])
= [F,T,F,T,F]

In [27]:
(arr==22) | (arr==44) 

array([False,  True, False,  True, False])

In [28]:
arr[(arr==22) | (arr==44)]

array([22, 44])

In [31]:
(arr>=20) & (arr<=40)

array([False,  True,  True, False, False])

In [32]:
arr[(arr>=20) & (arr<=40)]

array([22, 33])

In [36]:
~((arr==22) | (arr==44))

array([ True, False,  True, False,  True])

In [37]:
arr[~((arr==22) | (arr==44))]

array([11, 33, 55])