In [1]:
import numpy as np

In [37]:
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

### CRUD

### 추가

In [5]:
arr

array([11, 22, 33, 44, 55])

In [ ]:
np.append(arr, [100,200]) #추가할 값을 , 뒤로 배치

array([ 11,  22,  33,  44,  55, 100, 200])

In [9]:
np.insert(arr, 1,[1,2]) #(대상 array, 해당 인덱스 , 추가할 값)

array([11,  1,  2, 22, 33, 44, 55])

### 수정

공간 = 값

In [14]:
arr[1] = 200 # 해당 공간에 값을 주게 됨

In [20]:
arr

array([11, 10, 10, 44, 55])

In [17]:
arr[1:3] = [1,2]

In [19]:
arr[1:3] = 10

In [23]:
arr[3:5] = arr[3:5]+2

In [38]:
arr

array([11, 22, 33, 44, 55])

In [35]:
### Q) 30이상인 데이터를 기존 값에다 2를 더한 것으로 수정하시오.
### 결과; arr([11,22,35,46,57])
arr[arr>=30] = arr[arr>=30]+2
arr

array([11, 22, 35, 46, 57])

### 삭제

In [42]:
# np.delete(대상 배열,삭제할 인덱스)
# arr = np.delete(arr,[0,2]) ## arr= 을 추가해줘야 arr에 삭제가 적용
np.delete(arr,[0,2])

array([22, 44, 55])

In [ ]:
np.where(arr<30) #해당 조건의 인덱스를 반환됨

(array([0, 1]),)

In [48]:
np.where(arr>=30, 'A','B') #True = 'A', False = 'B'

array(['B', 'B', 'A', 'A', 'A'], dtype='<U1')

In [51]:
np.select([arr>=40,arr>=30,arr>=0],['A','B','C'],'F')

array(['C', 'C', 'B', 'A', 'A'], dtype='<U1')

In [54]:
arr

array([ 11, 100,  33,  44,  55])

### 정렬

In [ ]:
arr[1] = 100

In [55]:
np.sort(arr)

array([ 11,  33,  44,  55, 100])

In [ ]:
np.sort(arr)[::-1] # 내림차순은 따로 없음으로 역슬라이싱으로 해야함

array([100,  55,  44,  33,  11])

In [ ]:
np.argsort(arr) # array([100,  55,  44,  33,  11]) 정렬했을 때 인덱스 번호를 출력 

array([0, 2, 3, 4, 1])

In [ ]:
arr[np.argsort(arr)] # arr[[0, 2, 3, 4, 1]] 복수개 인덱싱

array([ 11,  33,  44,  55, 100])