In [6]:
import numpy as np

In [7]:
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

In [8]:
arr

array([11, 22, 33, 44, 55])

1) ndarray 멤버 함수 + np의 함수
2) np의 함수

In [9]:
arr.sum()

np.int64(165)

In [10]:
np.sum(arr)

np.int64(165)

In [11]:
arr.mean() #평균

np.float64(33.0)

In [12]:
np.mean(arr)

np.float64(33.0)

In [13]:
arr.max() #np.max(arr)

np.int64(55)

In [14]:
arr.min() #np.min(arr)

np.int64(11)

In [15]:
arr.argmax() #np.argmax(arr) 인덱스 max 값

np.int64(4)

In [16]:
arr.argmin() #np.argmin(arr) 인덱스 min 값

np.int64(0)

In [17]:
arr.std() #표준 편차

np.float64(15.556349186104045)

In [18]:
arr.var() #분산

np.float64(242.0)

In [19]:
np.median(arr) #데이터를 정렬했을 때 중앙(가운데) 값

np.float64(33.0)

In [20]:
np.quantile(arr,[0.25,0.5,0.75]) #4분위수 #데이터를 정렬했을 때 25%,50%,75% 에 해당하는 값

array([22., 33., 44.])

In [21]:
np.percentile(arr,[25,50,75]) #백분위수

array([22., 33., 44.])

In [22]:
a = np.array([10,20,20,20,30,30,40])
values, counts = np.unique(a, return_counts=True)
print(values)
print(counts)

[10 20 30 40]
[1 3 2 1]


In [23]:
a = np.array([10,20,20,20,30,30,40])
np.unique(a)

array([10, 20, 30, 40])

In [24]:
a = np.array([10,20,20,20,30,30,40,55,60,75,80,95])
bins = [0, 50, 70, 100]
freq, edges = np.histogram(a, bins=bins)
print( freq) 
print( edges )

[7 2 3]
[  0  50  70 100]


| 구간 | 의미 |
|------|------|
| 0 ~ 50 | **0 ≤ d < 50** |
| 50 ~ 70 | **50 ≤ d < 70** |
| 70 ~ 100 | **70 ≤ d < 100** |

쪽 경계 포함, 오른쪽 경계 제외

In [25]:
arr

array([11, 22, 33, 44, 55])