In [2]:
import numpy as np

In [53]:
# 국어, 영어, 수학 성적 데이터 (5명의 학생)
arr = np.array([
    [85, 92, 78],
    [90, 88, 95],
    [75, 80, 82],
    [95, 90, 88],
    [80, 75, 90]
])

In [45]:
arr

array([[85, 92, 78],
       [90, 88, 95],
       [75, 80, 82],
       [95, 90, 88],
       [80, 75, 90]])

## 속성

In [5]:
arr.ndim # 몇차원?

2

In [6]:
arr.size

15

In [7]:
arr.shape

(5, 3)

In [8]:
arr.shape[0] #(행,열) -> (0,1)

5

In [9]:
len(arr) # 행의 갯수

5

In [10]:
arr.T

array([[85, 90, 75, 95, 80],
       [92, 88, 80, 90, 75],
       [78, 95, 82, 88, 90]])

In [11]:
arr.dtype

dtype('int64')

## 인덱싱 슬라이싱

#### 인덱싱
- [행, 열]
- [행]

In [12]:
arr[0] # 0행

array([85, 92, 78])

In [13]:
arr[0,0] # 0행 0열

np.int64(85)

#### 슬라이싱

In [14]:
arr[1:] # 1행부터 끝까지

array([[90, 88, 95],
       [75, 80, 82],
       [95, 90, 88],
       [80, 75, 90]])

In [15]:
arr[1:,1:]

array([[88, 95],
       [80, 82],
       [90, 88],
       [75, 90]])

In [16]:
arr[[1,4]] # 복수개 행

array([[90, 88, 95],
       [80, 75, 90]])

In [17]:
print(arr[1])
print(arr[[1]])

[90 88 95]
[[90 88 95]]


In [18]:
## 수학 점수만 선택하시오.
arr[:, 2]

array([78, 95, 82, 88, 90])

In [19]:
arr[1:3, ::2]
# arr[1:3, [0,2]]

array([[90, 95],
       [75, 82]])

In [23]:
arr[[1,2],[0,2]] # pandas Ok(복수개 행, 복수개 컬럼)
# arr[1,0] --> 90
# arr[2,2] --> 82

array([90, 82])

In [24]:
arr[[1,2]][:,[0,2]] # 복수개 행을 두번쓰려면 나눠서 두번 써야 함

array([[90, 95],
       [75, 82]])

In [20]:
## Q)마지막 컬럼을 제외하고 추출하시오.
arr[:, :-1] # 인공지능(머신러닝 딥러닝 특성 데이터 추출)

array([[85, 92],
       [90, 88],
       [75, 80],
       [95, 90],
       [80, 75]])

In [25]:
arr[:,[-1]] # 인공지능(머신러닝 딥러닝 라벨 데이터 추출)

array([[78],
       [95],
       [82],
       [88],
       [90]])

### 2차원 데이터 boolean idexing(행단위)
- [[True, False,...]]

In [27]:
arr[[True,False,False,True,True]] #True인 행만 출력

array([[85, 92, 78],
       [95, 90, 88],
       [80, 75, 90]])

### 3차원

In [29]:
d3 = np.array( [ [[1,2],[3,4]] , [[5,6],[7,8]] ] ) #2X2X2
d3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

[면, 행, 열]

In [31]:
d3[0] #[면]

array([[1, 2],
       [3, 4]])

In [32]:
d3[0,0] #[면, 행]

array([1, 2])

In [33]:
d3[0, 1:]

array([[3, 4]])

### 2차원 연산

In [43]:
arr

array([[85, 92, 78],
       [94, 92, 99],
       [75, 80, 82],
       [95, 90, 88],
       [80, 75, 90]])

In [35]:
arr+2 #스칼라 합

array([[87, 94, 80],
       [92, 90, 97],
       [77, 82, 84],
       [97, 92, 90],
       [82, 77, 92]])

In [37]:
arr+[1,2,3] # 벡터 합

array([[86, 94, 81],
       [91, 90, 98],
       [76, 82, 85],
       [96, 92, 91],
       [81, 77, 93]])

In [38]:
arr*2

array([[170, 184, 156],
       [180, 176, 190],
       [150, 160, 164],
       [190, 180, 176],
       [160, 150, 180]])

In [ ]:
arr[1] = arr[1]+2  #기존 값에 더하기 한만큼 추가되어 수정됨

In [51]:
arr

array([[87, 92, 78],
       [94, 90, 97],
       [77, 80, 82],
       [97, 90, 88],
       [82, 75, 90]])

In [ ]:
arr[:,0] = arr[:,0] + 2 #기존 값에 더하기 한만큼 추가되어 수정됨

### 관계 연산자

In [54]:
arr = np.array([
    [85, 92, 78],
    [90, 88, 95],
    [75, 80, 82],
    [95, 90, 88],
    [80, 75, 90]
])

In [55]:
arr

array([[85, 92, 78],
       [90, 88, 95],
       [75, 80, 82],
       [95, 90, 88],
       [80, 75, 90]])

In [58]:
arr[:,0] >= 80

array([ True,  True, False,  True,  True])

In [59]:
arr[arr[:,0] >= 80] #국어 점수가 80점 이상인 행을 선택

array([[85, 92, 78],
       [90, 88, 95],
       [95, 90, 88],
       [80, 75, 90]])

In [63]:
# 영어 점수가 80점 이상 이거나 90점 이상인 행을 선택
arr[(arr[:,1] == 80) | (arr[:,1]==90)] # |(or)는 둘 중 하나라도 True면 True

array([[75, 80, 82],
       [95, 90, 88]])

In [69]:
# 수학 점수가 85점이상 95점 이하인 행을 선택
arr[(arr[:,2] >= 85) & (arr[:,2]<=95)]

array([[90, 88, 95],
       [95, 90, 88],
       [80, 75, 90]])

### 추가, 수정, 삭제, 정렬

### 추가

In [83]:
ax = np.array( [[1,2],[3,4]] )
ay = np.array( [[5,6],[7,8]] )

In [84]:
ax

array([[1, 2],
       [3, 4]])

In [85]:
ay

array([[5, 6],
       [7, 8]])

In [86]:
np.append(ax, ay) # axis=None 1차원으로 풀어서 append

array([1, 2, 3, 4, 5, 6, 7, 8])

In [87]:
np.append(ax, ay, axis=0) #axis=0  행으로 추가

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [88]:
np.append(ax, ay, axis=1) #axis=1 열로 추가

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [89]:
np.hstack( (ax,ay) ) # 수평으로 추가

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [90]:
np.vstack( (ax,ay) ) # 수직으로 추가

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### 삭제 
-  2차원에서는 axis= 의 값이 중요함
- axis=None 1차원 default 값
- axis=0    2차원 행
- axis=1    2차원 열

In [92]:
np.delete(arr, [1,3]) # axis=None 1차원으로 처리하여 1인덱스 3인덱스를 삭제 처리함

array([85, 78, 88, 95, 75, 80, 82, 95, 90, 88, 80, 75, 90])

In [94]:
np.delete(arr, [1,3], axis=0) #axis=0 1행과 3행을 삭제

array([[85, 92, 78],
       [75, 80, 82],
       [80, 75, 90]])

In [95]:
np.delete(arr, [0,2], axis=1) #axis=1 삭제 대상 인덱스가 컬럼이 됨 

array([[92],
       [88],
       [80],
       [90],
       [75]])

In [93]:
arr

array([[85, 92, 78],
       [90, 88, 95],
       [75, 80, 82],
       [95, 90, 88],
       [80, 75, 90]])

### 정렬

In [97]:
np.sort(arr) # default: -1 ,1 과 같다 (행 단위 정렬)

array([[78, 85, 92],
       [88, 90, 95],
       [75, 80, 82],
       [88, 90, 95],
       [75, 80, 90]])

In [99]:
np.sort(arr, axis=None)

array([75, 75, 78, 80, 80, 82, 85, 88, 88, 90, 90, 90, 92, 95, 95])

In [100]:
np.sort(arr, axis=0) # 국영수 컬럼(열) 단위로 가장 낮은 순 -> 가장 높은 순으로 정렬된 값

array([[75, 75, 78],
       [80, 80, 82],
       [85, 88, 88],
       [90, 90, 90],
       [95, 92, 95]])

In [101]:
np.sort(arr, axis=1) # 국영수 행 단위로 가장 낮은 순 -> 가장 높은 순으로 정렬된 값

array([[78, 85, 92],
       [88, 90, 95],
       [75, 80, 82],
       [88, 90, 95],
       [75, 80, 90]])

In [98]:
arr

array([[85, 92, 78],
       [90, 88, 95],
       [75, 80, 82],
       [95, 90, 88],
       [80, 75, 90]])

### 통계
- axis=None: 1차원 벡터로 통계 (default 값)
- axis=0: 컬럼별(열) 통계
- axis=1: 행별 통계

In [103]:
arr.sum()

np.int64(1283)

In [104]:
np.sum(arr)

np.int64(1283)

In [106]:
arr.sum(axis=0) # 컬럼별(열) 총합

array([425, 425, 433])

In [108]:
np.sum(arr, axis=0)

array([425, 425, 433])

In [112]:
arr.sum(axis=1)

array([255, 273, 237, 273, 245])

In [110]:
np.sum(arr, axis=1) # 행 별 총합

array([255, 273, 237, 273, 245])

In [113]:
arr.mean() #전체 평균

np.float64(85.53333333333333)

In [114]:
arr.mean(axis=0) #np.mean(arr, axis=0) 평균 

array([85. , 85. , 86.6])

In [116]:
arr.mean(axis=1).round(2)

array([85.  , 91.  , 79.  , 91.  , 81.67])

In [117]:
arr.max()

np.int64(95)

In [118]:
arr.max(axis=0)

array([95, 92, 95])

In [119]:
arr.max(axis=1)

array([92, 95, 82, 95, 90])

In [130]:
arr

array([[85, 92, 78],
       [90, 88, 95],
       [75, 80, 82],
       [95, 90, 88],
       [80, 75, 90]])

In [120]:
# 인덱스 값
arr.argmax() #딥러닝 사용 多

np.int64(5)

In [121]:
arr.argmax(axis=0) #컬럼별 가장 큰 인덱스의 값

array([3, 0, 1])

In [122]:
# 머신러닝 딥러닝 분류 쪽 사용 多
arr.argmax(axis=1) #행 별 가장 큰 인덱스의 값

array([1, 2, 2, 0, 2])

In [123]:
np.argmax(arr, axis=1)

array([1, 2, 2, 0, 2])

In [125]:
np.median(arr) #전체에 대한 중앙 값

np.float64(88.0)

In [127]:
np.median(arr, axis=0) # 각 컬럼별 중앙 값

array([85., 88., 88.])

In [128]:
for n in arr:
    print(n) #행 단위로 loop 돌림

[85 92 78]
[90 88 95]
[75 80 82]
[95 90 88]
[80 75 90]


In [129]:
for k,e,m in arr:
    print(k,e,m)

85 92 78
90 88 95
75 80 82
95 90 88
80 75 90


In [107]:
arr

array([[85, 92, 78],
       [90, 88, 95],
       [75, 80, 82],
       [95, 90, 88],
       [80, 75, 90]])

- 이변수(2개의 컬럼에 대해 분석) : 상관 관계, 단일선형, 교차분석, 집계
- 다변수(3개의 컬럼 이상) :  주성분(PCA), 다중선형, 균집 등....

```text
r이 -1.0과 -0.7 사이이면, 강한 음적 선형관계,
r이 -0.7과 -0.3 사이이면, 뚜렷한 음적 선형관계,
r이 -0.3과 -0.1 사이이면, 약한 음적 선형관계,
r이 -0.1과 +0.1 사이이면, 거의 무시될 수 있는 선형관계,
r이 +0.1과 +0.3 사이이면, 약한 양적 선형관계,
r이 +0.3과 +0.7 사이이면, 뚜렷한 양적 선형관계,
r이 +0.7과 +1.0 사이이면, 강한 양적 선형관계

In [132]:
np.corrcoef(arr, rowvar=False)

array([[ 1.        ,  0.72357287,  0.40158725],
       [ 0.72357287,  1.        , -0.20200585],
       [ 0.40158725, -0.20200585,  1.        ]])

### 데이터 읽기

In [134]:
# birthArr = np.loadtxt('data/births.csv',delimiter=',',dtype=np.int64, skiprows=1)
birthArr = np.loadtxt('data/births.csv',delimiter=',',dtype=np.int64)
birthArr

array([[   1880,   90993,  110491],
       [   1881,   91954,  100745],
       [   1882,  107850,  113688],
       [   1883,  112321,  104629],
       [   1884,  129022,  114445],
       [   1885,  133055,  107800],
       [   1886,  144535,  110784],
       [   1887,  145982,  101414],
       [   1888,  178627,  120853],
       [   1889,  178366,  110584],
       [   1890,  190377,  111025],
       [   1891,  185482,  101196],
       [   1892,  212346,  122037],
       [   1893,  212906,  112317],
       [   1894,  222922,  115772],
       [   1895,  233630,  117398],
       [   1896,  237920,  119570],
       [   1897,  234202,  112758],
       [   1898,  258770,  122693],
       [   1899,  233023,  106212],
       [   1900,  299828,  150499],
       [   1901,  239348,  106471],
       [   1902,  264077,  122659],
       [   1903,  261973,  119234],
       [   1904,  275371,  128125],
       [   1905,  291629,  132319],
       [   1906,  295303,  133159],
       [   1907,  318566,  1

1. 행의 갯수를 구하시오.
2. 남아, 여아 출생 평균을 구하시오.
3. 남아, 여아 표준편차를 구하시오.
4. 여아 사분위수를 구하시오.
5. 남아 여아 상관관계를 구하시오.
6. 2000년대 데이터를 구하시오
7. 남아 수가 150000명 이상인 연도만 추출하시오
8. 연도별 총 출생아 수(남아+여아)를 새로운 열로 추가하시오.

In [167]:
#1. 행의 갯수를 구하시오.
print(birthArr.shape[0])
print(len(birthArr))

132
132


In [169]:
#2. 남아, 여아 출생 평균을 구하시오.
birthArr[:,1:].mean(axis=0).round(2)

array([1225776.07, 1245399.21])

In [174]:
# 3. 남아, 여아 표준편차를 구하시오.
birthArr[:,1:].std(axis=0).round(2)


array([643100.31, 737194.5 ])

In [177]:
# 4. 여아 사분위수를 구하시오.
np.quantile(birthArr[:,2],[0.25,0.5,0.75])

array([ 491904. , 1493092. , 1904686.5])

In [178]:
# 5. 남아 여아 상관관계를 구하시오.
np.corrcoef(birthArr[:,1:], rowvar=False)

array([[1.        , 0.99630013],
       [0.99630013, 1.        ]])

In [180]:
# 6. 2000년대 데이터를 구하시오
birthArr[birthArr[:,0]>=2000]

array([[   2000, 1814601, 1962406],
       [   2001, 1799049, 1941251],
       [   2002, 1795206, 1939815],
       [   2003, 1825359, 1973434],
       [   2004, 1834145, 1982794],
       [   2005, 1845379, 1994841],
       [   2006, 1898463, 2052377],
       [   2007, 1919408, 2072139],
       [   2008, 1887234, 2036289],
       [   2009, 1832925, 1979303],
       [   2010, 1772738, 1913851],
       [   2011, 1753500, 1893230]])

In [189]:
# 7. 남아 수가 150000명 이상인 연도만 추출하시오
birthArr[birthArr[:,1]>=150000][:,0]

array([1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898,
       1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909,
       1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920,
       1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931,
       1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942,
       1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953,
       1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964,
       1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975,
       1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986,
       1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997,
       1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008,
       2009, 2010, 2011])

In [ ]:
# 8. 연도별 총 출생아 수(남아+여아)를 새로운 열로 추가하시오.
total = birthArr[:,1] + birthArr[:,2]
# total.reshape(-1,1)
# np.hstack((birthArr,total.reshape(-1,1)))
np.c_[birthArr, total] # 속성, 벡터로 가능

array([[   1880,   90993,  110491,  201484],
       [   1881,   91954,  100745,  192699],
       [   1882,  107850,  113688,  221538],
       [   1883,  112321,  104629,  216950],
       [   1884,  129022,  114445,  243467],
       [   1885,  133055,  107800,  240855],
       [   1886,  144535,  110784,  255319],
       [   1887,  145982,  101414,  247396],
       [   1888,  178627,  120853,  299480],
       [   1889,  178366,  110584,  288950],
       [   1890,  190377,  111025,  301402],
       [   1891,  185482,  101196,  286678],
       [   1892,  212346,  122037,  334383],
       [   1893,  212906,  112317,  325223],
       [   1894,  222922,  115772,  338694],
       [   1895,  233630,  117398,  351028],
       [   1896,  237920,  119570,  357490],
       [   1897,  234202,  112758,  346960],
       [   1898,  258770,  122693,  381463],
       [   1899,  233023,  106212,  339235],
       [   1900,  299828,  150499,  450327],
       [   1901,  239348,  106471,  345819],
       [  

In [195]:
print('년도','남아','여아','총 출생아 수',sep="\t")
print("="*40)
for y,b,g,t in np.hstack((birthArr,total.reshape(-1,1))):
    print(y,b,g,t, sep="\t")

년도	남아	여아	총 출생아 수
1880	90993	110491	201484
1881	91954	100745	192699
1882	107850	113688	221538
1883	112321	104629	216950
1884	129022	114445	243467
1885	133055	107800	240855
1886	144535	110784	255319
1887	145982	101414	247396
1888	178627	120853	299480
1889	178366	110584	288950
1890	190377	111025	301402
1891	185482	101196	286678
1892	212346	122037	334383
1893	212906	112317	325223
1894	222922	115772	338694
1895	233630	117398	351028
1896	237920	119570	357490
1897	234202	112758	346960
1898	258770	122693	381463
1899	233023	106212	339235
1900	299828	150499	450327
1901	239348	106471	345819
1902	264077	122659	386736
1903	261973	119234	381207
1904	275371	128125	403496
1905	291629	132319	423948
1906	295303	133159	428462
1907	318566	146833	465399
1908	334313	154344	488657
1909	347228	163999	511227
1910	396501	194218	590719
1911	418299	225968	644267
1912	558103	429945	988048
1913	624518	512557	1137075
1914	761548	654762	1416310
1915	983874	848603	1832477
1916	1044323	890099	1934422
1917	1081280	92551