In [1]:
import numpy as np

In [2]:
birthArr = np.loadtxt('data/births.csv',delimiter=',',dtype=np.int64)
birthArr

array([[   1880,   90993,  110491],
       [   1881,   91954,  100745],
       [   1882,  107850,  113688],
       [   1883,  112321,  104629],
       [   1884,  129022,  114445],
       [   1885,  133055,  107800],
       [   1886,  144535,  110784],
       [   1887,  145982,  101414],
       [   1888,  178627,  120853],
       [   1889,  178366,  110584],
       [   1890,  190377,  111025],
       [   1891,  185482,  101196],
       [   1892,  212346,  122037],
       [   1893,  212906,  112317],
       [   1894,  222922,  115772],
       [   1895,  233630,  117398],
       [   1896,  237920,  119570],
       [   1897,  234202,  112758],
       [   1898,  258770,  122693],
       [   1899,  233023,  106212],
       [   1900,  299828,  150499],
       [   1901,  239348,  106471],
       [   1902,  264077,  122659],
       [   1903,  261973,  119234],
       [   1904,  275371,  128125],
       [   1905,  291629,  132319],
       [   1906,  295303,  133159],
       [   1907,  318566,  1

# 1. 남아 수가 평균보다 많은 연도만 출력하시오

In [6]:
a = np.mean( birthArr[:,1] )
birthArr[birthArr[:,1]>a][:,0]

array([1921, 1924, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950,
       1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961,
       1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972,
       1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983,
       1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994,
       1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
       2006, 2007, 2008, 2009, 2010, 2011])

2. 남아출생이 가장많은 top5를 구하시요(년도와 남아수)

In [11]:
r = np.argsort( birthArr[:,1] )[:-6:-1]
birthArr[ r , :2 ]

array([[   1957, 2044160],
       [   1959, 2023044],
       [   1960, 2022093],
       [   1961, 2017316],
       [   1958, 2010884]])

3. 남아율(%) 을 구하고 각년도별
남아수가 차지하는비율컬럼을 추가하시요

In [ ]:
np.set_printoptions(precision=4, suppress=True)
# np.set_printoptions(formatter=None)

In [18]:
brate = birthArr[:,1]/(birthArr[:,1]+birthArr[:,2])*100
np.c_[birthArr, brate]

array([[   1880.    ,   90993.    ,  110491.    ,      45.1614],
       [   1881.    ,   91954.    ,  100745.    ,      47.719 ],
       [   1882.    ,  107850.    ,  113688.    ,      48.6824],
       [   1883.    ,  112321.    ,  104629.    ,      51.7728],
       [   1884.    ,  129022.    ,  114445.    ,      52.9936],
       [   1885.    ,  133055.    ,  107800.    ,      55.2428],
       [   1886.    ,  144535.    ,  110784.    ,      56.6096],
       [   1887.    ,  145982.    ,  101414.    ,      59.0074],
       [   1888.    ,  178627.    ,  120853.    ,      59.6457],
       [   1889.    ,  178366.    ,  110584.    ,      61.729 ],
       [   1890.    ,  190377.    ,  111025.    ,      63.1638],
       [   1891.    ,  185482.    ,  101196.    ,      64.7005],
       [   1892.    ,  212346.    ,  122037.    ,      63.5038],
       [   1893.    ,  212906.    ,  112317.    ,      65.4646],
       [   1894.    ,  222922.    ,  115772.    ,      65.8181],
       [   1895.    ,  23