In [1]:
import numpy as np

In [2]:
names = np.array( ['홍길동','이순신','임꺽정','정도전','이황', '이이', '김철수', '김영희', '김세종','박문수'] )
kor = np.array( [60,55,70,30,20,90,70,20,90,15 ] )
print(names)
print(kor)

['홍길동' '이순신' '임꺽정' '정도전' '이황' '이이' '김철수' '김영희' '김세종' '박문수']
[60 55 70 30 20 90 70 20 90 15]


01. 국어점수가 가장큰값을 구하시요(아래와 같이 출력)

In [ ]:

mx =np.max(kor)
idx = np.where(kor==mx)
# print( names[ idx ] )  #name[ [5,8] ]
# print( kor[idx] ) #kor[ [5,8] ]
for n,k in zip( names[ idx ] ,kor[idx] ):
    print( n,k ,sep='\t')

이이	90
김세종	90


### boolean indexing

In [14]:
kor==mx

array([False, False, False, False, False,  True, False, False,  True,
       False])

In [16]:
names[ kor==mx ]
#names[ [False, False, False, False, False,  True, False, False,  True,False] ]

array(['이이', '김세종'], dtype='<U3')

In [17]:
mx=kor.max()
mname=names[ kor==mx ]
for i in mname:
    print(i,mx)

이이 90
김세종 90


2. 국어점수가 80점 이상인 값을 구하시오.

In [18]:
kor[kor>=80]

array([90, 90])

3. 국어점수가 50점이상 80이하인 값을 구하시요

In [19]:
kor[(50<=kor) & (kor<=80)]

array([60, 55, 70, 70])

4. 국어점수의 평균을 구하시오

In [20]:
kor.mean()

np.float64(52.0)

5. 국어점수의 총합을 구하시요.

In [21]:
np.sum(kor)

np.int64(520)

6. 국어점수의 표준편차를 구하시요

In [22]:
np.std(kor)

np.float64(27.40437921208944)

7. 국어점수 top5를 구하시요

In [24]:
np.sort(kor)[:-6:-1]

array([90, 90, 70, 70, 60])

8. 국어점수가 40점 이하인 데이터를 삭제하시오

In [26]:
np.where(kor <= 40)

(array([3, 4, 7, 9]),)

In [ ]:
np.delete(kor, kor<=40) #표준이 아니므로 조심 version 1.19.0 이상만 사용 가능

In [ ]:
np.delete( kor, np.where(kor <= 40) )# 표준

array([60, 55, 70, 90, 70, 90])

9. 국어점수가 50점이상인 데이터에 가산점 10%를 
미만인경우는 20%를 부여하시요

In [3]:
np.where(kor>=50, kor*1.1, kor*1.2)

array([66. , 60.5, 77. , 36. , 24. , 99. , 77. , 24. , 99. , 18. ])

10. 국어점수가 70점이상이면 '합격', 아니면 '불합격' 으로
아래와 같이 출력하시요
```
점수 합격여부
------------------
60 '불합격'
55 '불합격'
...

In [ ]:
pass_fail = np.where(kor>=70, '합격', '불합격')
print('점수','합격여부', sep='\t')
print('-'*20)
for a, b in zip(kor, pass_fail):
    print(a,b,sep='\t')

점수	합격여부
--------------------
60	불합격
55	불합격
70	합격
30	불합격
20	불합격
90	합격
70	합격
20	불합격
90	합격
15	불합격


In [11]:
tf=np.where(kor>=70,'합격','불합격')
for idx, v in enumerate(tf):
    print( kor[idx], v )
# for i in range(0,len(kor)):
#     print(f"{kor[i]} '{tf[i]}'")

60 불합격
55 불합격
70 합격
30 불합격
20 불합격
90 합격
70 합격
20 불합격
90 합격
15 불합격


In [8]:
mylist = [10,20,30,40,50]
for idx, v in enumerate(mylist):
    print( idx, v )

0 10
1 20
2 30
3 40
4 50


# 11. 각 데이터의 개수 확인 방법(ex 60점은 몇개...)

In [14]:
np.unique(kor, return_counts=True)

(array([15, 20, 30, 55, 60, 70, 90]), array([1, 2, 1, 1, 1, 2, 2]))

11. 각 데이터의 개수 확인 방법(ex 60점은 몇개...)

In [ ]:
values, counts = np.unique(kor, return_counts=True)
for v, c in zip( values, counts ):
    print( f'{v}점은 {c}개')

15점은 1개
20점은 2개
30점은 1개
55점은 1개
60점은 1개
70점은 2개
90점은 2개


12. 국어점수의 범위(0~50,50~70,70~100)별 돗수를 구하시요 
( 범위, 0~50,50~70,70~100)

In [18]:
ran = [0,50,70,100]
np.histogram(kor,ran)

(array([4, 2, 4]), array([  0,  50,  70, 100]))

edges[1:] =  [50,  70, 100]
edges[:-1] = [0,  50,  70]
freq =       [4, 2, 4]

In [19]:
bins = [0, 50, 70, 100]
freq, edges = np.histogram(kor, bins=bins)

print('범위 \t갯수 \n-------------')
for a, b, c in zip(edges[1:], edges[:-1], freq):
    print(f'{b}~{a}\t {c}')

범위 	갯수 
-------------
0~50	 4
50~70	 2
70~100	 4
