```
names = np.array( ['홍길동','이순신','임꺽정','정도전','이황', '이이', '김철수', '김영희', '김세종','박문수']
kor = np.array( [60,55,70,30,20,90,70,20,90,15 ] )
kor

1. 국어점수가 가장큰값을 구하시요(아래와 같이 출력)
이이 90
김세종 90

2. 국어점수가 80점 이상인 값을 구하시요
3. 국어점수가 50점이상 80이하인 값을 구하시요
4. 국어점수의 평균을 구하시요.
5. 국어점수의 총합을 구하시요.
6. 국어점수의 표준편차를 구하시요
7. 국어점수 top5를 구하시요
8. 국어점수가 40점이하인 데이터를 삭제하시요(실데이터 적용X)
9. 국어점수가 50점이상인 데이터에 가산점 10%를  미만인경우는 20%를 부여하시요
10. 국어점수가 70점이상이면 '합격', 아니면 '불합격' 으로
아래와 같이 출력하시요

점수 합격여부
------------------
60 '불합격'
55 '불합격'
...

11.각 데이터 갯수를 구하시요
값  갯수
------------
60 1
55 1
70 2

12. 국어점수의 범위(0~50,50~70,70~100)별 돗수를 구하시요 
( 범위, 0~50,50~70,70~100)

In [1]:
import numpy as np

In [2]:
names = np.array( ['홍길동','이순신','임꺽정','정도전','이황', '이이', '김철수', '김영희', '김세종','박문수'] )
kor = np.array( [60,55,70,30,20,90,70,20,90,15 ] )
kor

array([60, 55, 70, 30, 20, 90, 70, 20, 90, 15])

1. 국어점수가 가장큰값을 구하시오. (아래와 같이 출력)  
김철수 90  
김세종 90  

In [42]:
res = np.where(kor==np.max(kor))

for a, b in zip(names[res], kor[res]):
    print(a, b)


이이 90
김세종 90


2. 국어점수가 80점 이상인 값을 구하시오.

In [59]:
kor[kor>=80]

array([90, 90])

3. 국어점수가 50점이상 80이하인 값을 구하시요

In [61]:
kor[(80>=kor) & (kor>=50)]

array([60, 55, 70, 70])

4. 국어점수의 평균을 구하시요.

In [62]:
np.average(kor)

np.float64(52.0)

5. 국어점수의 총합을 구하시요.

In [63]:
np.sum(kor)

np.int64(520)

6. 국어점수의 표준편차를 구하시요

In [64]:
np.std(kor)

np.float64(27.40437921208944)

7. 국어점수 top5를 구하시요

In [ ]:
np.sort(kor)[-1:-6:-1]

array([90, 90, 70, 70, 60])

8. 국어점수가 40점이하인 데이터를 삭제하시요(실데이터 적용X)

In [87]:
kor_delete = np.delete(kor, np.where(kor<=40))
print(kor_delete)

[60 55 70 90 70 90]


9. 국어점수가 50점이상인 데이터에 가산점 10%를 
미만인경우는 20%를 부여하시요

In [91]:
np.where(kor>=50, kor*1.1, kor*1.2)

array([66. , 60.5, 77. , 36. , 24. , 99. , 77. , 24. , 99. , 18. ])

10. 국어점수가 70점이상이면 '합격', 아니면 '불합격' 으로
아래와 같이 출력하시요
```
점수 합격여부
------------------
60 '불합격'
55 '불합격'
...

In [32]:
pass_fail = np.where(kor>=70, '합격', '불합격')

print('점수 \t 합격여부 \n----------------')
for a, b in zip(kor, pass_fail):
    print(f'{a} \t {b}')

점수 	 합격여부 
----------------
60 	 불합격
55 	 불합격
70 	 합격
30 	 불합격
20 	 불합격
90 	 합격
70 	 합격
20 	 불합격
90 	 합격
15 	 불합격


11.각 데이터 갯수를 구하시요
```
값  갯수
------------
60 1
55 1
70 2

In [ ]:
values, counts = np.unique(kor, return_counts=True)

print('값 \t갯수 \n-------------')
for a, b in zip(values, counts):
    print(f'{a}\t {b}')

값 	갯수 
-------------
15	 1
20	 2
30	 1
55	 1
60	 1
70	 2
90	 2


12. 국어점수의 범위(0~50,50~70,70~100)별 갯수를 구하시요 
( 범위, 0~50,50~70,70~100)

In [28]:
bins = [0, 50, 70, 100]
freq, edges = np.histogram(kor, bins=bins)

print('범위 \t갯수 \n-------------')
for a, b, c in zip(edges[1:], edges[:-1], freq):
    print(f'{b}~{a}\t {c}')

범위 	갯수 
-------------
0~50	 4
50~70	 2
70~100	 4
